// Génération_Code_Application/Codex5.3_PrepPro_Aesthetic/src/components/cart/CartPage.tsx
import { createSignal, onMount, For, Show } from "solid-js";
import { useStore } from "@nanostores/solid";
import {
  cartItems,
  cartTotalCents,
  clearCart,
  initCartFromStorage,
  removeFromCart,
  updateCartQuantity,
} from "@/stores/cart";
import { formatPrice } from "@/lib/format";
import type { PublicUser } from "@/lib/auth/types";

type Props = {
  user: PublicUser | null;
};

export default function CartPage(props: Props) {
  const items = useStore(cartItems);
  const totalCents = useStore(cartTotalCents);
  const [balanceCents, setBalanceCents] = createSignal(
    props.user?.balanceCents ?? null,
  );
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal("");
  const [success, setSuccess] = createSignal("");
  const [lastOrderId, setLastOrderId] = createSignal<number | null>(null);
  const [lastInvoiceNumber, setLastInvoiceNumber] = createSignal("");

  onMount(() => {
    initCartFromStorage();
    if (props.user) {
      refreshBalance();
    }
  });

  async function refreshBalance() {
    try {
      const res = await fetch("/api/auth/me");
      const json = await res.json();
      if (json.user?.balanceCents != null) {
        setBalanceCents(json.user.balanceCents);
      }
    } catch {
      /* keep SSR value */
    }
  }

  async function handleCheckout() {
    setError("");
    setSuccess("");
    setLastOrderId(null);
    setLastInvoiceNumber("");

    if (!props.user) {
      window.location.href = `/login?next=${encodeURIComponent("/cart")}`;
      return;
    }

    if (items().length === 0) {
      setError("Your cart is empty.");
      return;
    }

    setLoading(true);
    try {
      const res = await fetch("/api/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          items: items().map((i) => ({
            productId: i.productId,
            quantity: i.quantity,
          })),
        }),
      });
      const json = await res.json();

      if (!res.ok) {
        setError(json.error ?? "Checkout failed.");
        if (json.user?.balanceCents != null) {
          setBalanceCents(json.user.balanceCents);
        }
        return;
      }

      setSuccess(json.message ?? "Order placed successfully!");
      setBalanceCents(json.balanceCents ?? json.user?.balanceCents ?? null);
      if (json.order?.id) {
        setLastOrderId(json.order.id);
        setLastInvoiceNumber(json.order.invoiceNumber ?? "");
      }
      clearCart();
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  const canAfford = () => {
    const bal = balanceCents();
    return bal !== null && bal >= totalCents();
  };

  return (
    <div class="mx-auto max-w-3xl">
      <h1 class="font-display text-3xl font-semibold text-ink">Shopping cart</h1>
      <p class="mt-2 text-muted">
        Review your items and complete a simulated checkout from your account
        balance.
      </p>

      <Show when={props.user && balanceCents() !== null}>
        <div class="mt-6 rounded-xl border border-brand-200 bg-brand-50/80 px-4 py-3">
          <p class="text-sm text-muted">Account balance</p>
          <p class="text-xl font-semibold text-brand-800">
            {formatPrice(balanceCents()!)}
          </p>
        </div>
      </Show>

      <Show when={!props.user}>
        <p class="mt-6 rounded-xl border border-brand-200 bg-white px-4 py-3 text-sm text-muted">
          <a href="/login?next=%2Fcart" class="font-semibold text-brand-700 hover:underline">
            Sign in
          </a>{" "}
          to checkout using your account balance.
        </p>
      </Show>

      <Show when={lastOrderId()}>
        <div
          class="mt-10 rounded-2xl border border-brand-200 bg-brand-50 p-6 shadow-sm"
          role="status"
        >
          <h2 class="font-display text-xl font-semibold text-brand-800">
            Order confirmed
          </h2>
          <p class="mt-2 text-sm text-brand-900">{success()}</p>
          <p class="mt-2 text-sm text-muted">
            Invoice{" "}
            <span class="font-mono font-medium text-ink">{lastInvoiceNumber()}</span>
          </p>
          <div class="mt-4 flex flex-wrap gap-3">
            <a
              href={`/api/invoices/${lastOrderId()}`}
              class="inline-flex rounded-full bg-brand-700 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-brand-800"
              download
            >
              Download invoice (PDF)
            </a>
            <a
              href="/catalog"
              class="inline-flex rounded-full border border-brand-300 px-5 py-2.5 text-sm font-semibold text-brand-800 hover:bg-white"
            >
              Continue shopping
            </a>
          </div>
        </div>
      </Show>

      <Show
        when={items().length > 0}
        fallback={
          <Show when={!lastOrderId()}>
            <div class="mt-10 rounded-2xl border border-dashed border-brand-200 bg-brand-50/50 p-10 text-center">
              <p class="text-muted">Your cart is empty.</p>
              <a
                href="/catalog"
                class="mt-4 inline-block rounded-full bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-brand-700"
              >
                Browse products
              </a>
            </div>
          </Show>
        }
      >
        <ul class="mt-8 divide-y divide-brand-100 rounded-2xl border border-brand-100 bg-white shadow-sm">
          <For each={items()}>
            {(item) => (
              <li class="flex flex-wrap items-center justify-between gap-4 px-5 py-4">
                <div class="min-w-0 flex-1">
                  <p class="font-semibold text-ink">{item.name}</p>
                  <p class="text-sm text-muted">
                    {formatPrice(item.priceCents)} each
                  </p>
                </div>
                <div class="flex items-center gap-3">
                  <div class="flex items-center rounded-lg border border-brand-200">
                    <button
                      type="button"
                      class="px-3 py-1.5 text-brand-800 hover:bg-brand-50"
                      aria-label="Decrease quantity"
                      onClick={() =>
                        updateCartQuantity(item.productId, item.quantity - 1)
                      }
                    >
                      −
                    </button>
                    <span class="min-w-[2rem] text-center text-sm font-medium">
                      {item.quantity}
                    </span>
                    <button
                      type="button"
                      class="px-3 py-1.5 text-brand-800 hover:bg-brand-50"
                      aria-label="Increase quantity"
                      onClick={() =>
                        updateCartQuantity(item.productId, item.quantity + 1)
                      }
                    >
                      +
                    </button>
                  </div>
                  <span class="w-24 text-right font-semibold text-ink">
                    {formatPrice(item.priceCents * item.quantity)}
                  </span>
                  <button
                    type="button"
                    class="text-sm text-red-600 hover:underline"
                    onClick={() => removeFromCart(item.productId)}
                  >
                    Remove
                  </button>
                </div>
              </li>
            )}
          </For>
        </ul>

        <div class="mt-6 rounded-2xl border border-brand-100 bg-white p-6 shadow-sm">
          <div class="flex items-center justify-between text-lg font-semibold text-ink">
            <span>Order total</span>
            <span>{formatPrice(totalCents())}</span>
          </div>

          <Show when={props.user && balanceCents() !== null && !canAfford()}>
            <p class="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">
              Insufficient balance. You have {formatPrice(balanceCents()!)} but need{" "}
              {formatPrice(totalCents())}.
            </p>
          </Show>

          <Show when={error()}>
            <p class="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">
              {error()}
            </p>
          </Show>

          <div class="mt-6 flex flex-wrap gap-3">
            <button
              type="button"
              disabled={loading() || (props.user !== null && !canAfford())}
              onClick={handleCheckout}
              class="rounded-full bg-brand-600 px-6 py-3 text-sm font-semibold text-white transition hover:bg-brand-700 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {loading()
                ? "Processing…"
                : props.user
                  ? "Complete checkout"
                  : "Sign in to checkout"}
            </button>
            <a
              href="/#products"
              class="rounded-full border border-brand-300 px-6 py-3 text-sm font-semibold text-brand-800 hover:bg-brand-50"
            >
              Continue shopping
            </a>
          </div>
          <p class="mt-3 text-xs text-muted">
            Simulated checkout — no payment gateway. Your account balance will be
            debited when the order succeeds.
          </p>
        </div>
      </Show>
    </div>
  );
}

// Websites/Cursor_AuraWear/frontend/src/pages/CartPage.tsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import * as checkoutApi from "../api/checkout";
import { ApiError } from "../api/client";
import { useAuth } from "../context/AuthContext";
import { useCart } from "../context/CartContext";
import { formatCurrency } from "../utils/format";

export default function CartPage() {
  const { items, itemCount, subtotal, updateQuantity, removeItem, clearCart } = useCart();
  const { user, isAuthenticated, refreshUser } = useAuth();
  const navigate = useNavigate();

  const [checkingOut, setCheckingOut] = useState(false);
  const [downloadingInvoice, setDownloadingInvoice] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [completedOrder, setCompletedOrder] = useState<{
    orderId: number;
    invoiceNumber: string;
  } | null>(null);

  async function handleCheckout() {
    if (!isAuthenticated) {
      navigate("/login", { state: { from: "/cart" } });
      return;
    }
    if (items.length === 0) return;

    setCheckingOut(true);
    setError("");
    setSuccess("");
    setCompletedOrder(null);
    try {
      const result = await checkoutApi.checkout(items);
      clearCart();
      await refreshUser();
      setCompletedOrder({ orderId: result.order_id, invoiceNumber: result.invoice_number });
      setSuccess(
        `${result.message} Invoice ${result.invoice_number}. Total charged: ${formatCurrency(result.total)}. New balance: ${formatCurrency(result.new_balance)}.`,
      );
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Checkout failed");
    } finally {
      setCheckingOut(false);
    }
  }

  async function handleDownloadInvoice() {
    if (!completedOrder) return;
    setDownloadingInvoice(true);
    setError("");
    try {
      await checkoutApi.downloadInvoice(completedOrder.orderId, completedOrder.invoiceNumber);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Could not download invoice");
    } finally {
      setDownloadingInvoice(false);
    }
  }

  const balance = user ? parseFloat(user.balance) : 0;
  const canAfford = isAuthenticated && balance >= subtotal;

  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="font-display text-3xl font-semibold text-aura-950">Shopping cart</h1>
      <p className="mt-2 text-sm text-aura-600">
        {itemCount === 0 ? "Your cart is empty." : `${itemCount} item${itemCount !== 1 ? "s" : ""} in your cart`}
      </p>

      {success && (
        <div className="mt-6 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-800" role="status">
          <p>{success}</p>
          {completedOrder && (
            <button
              type="button"
              onClick={handleDownloadInvoice}
              disabled={downloadingInvoice}
              className="mt-3 inline-flex rounded-full bg-aura-950 px-5 py-2 text-sm font-semibold text-aura-50 transition hover:bg-aura-800 disabled:opacity-60"
            >
              {downloadingInvoice ? "Preparing PDF…" : "Download invoice (PDF)"}
            </button>
          )}
          <p className="mt-3">
            <Link to="/" className="font-semibold underline">
              Continue shopping
            </Link>
          </p>
        </div>
      )}

      {error && (
        <p className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">
          {error}
        </p>
      )}

      {items.length === 0 && !success ? (
        <div className="mt-10 text-center">
          <Link
            to="/#shop"
            className="inline-flex rounded-full bg-aura-950 px-6 py-3 text-sm font-semibold text-aura-50 hover:bg-aura-800"
          >
            Browse products
          </Link>
        </div>
      ) : (
        items.length > 0 && (
          <div className="mt-8 grid gap-8 lg:grid-cols-3">
            <ul className="space-y-4 lg:col-span-2">
              {items.map((item) => (
                <li
                  key={item.productId}
                  className="flex gap-4 rounded-2xl border border-aura-200 bg-white p-4 shadow-sm"
                >
                  <div className="h-24 w-20 shrink-0 overflow-hidden rounded-lg bg-aura-100">
                    {item.image_url ? (
                      <img src={item.image_url} alt="" className="h-full w-full object-cover" />
                    ) : (
                      <div className="h-full w-full bg-aura-200" />
                    )}
                  </div>
                  <div className="min-w-0 flex-1">
                    <h2 className="font-medium text-aura-950">{item.name}</h2>
                    <p className="text-sm text-aura-600">{formatCurrency(item.price)} each</p>
                    <div className="mt-3 flex flex-wrap items-center gap-3">
                      <div className="flex items-center rounded-lg border border-aura-300">
                        <button
                          type="button"
                          onClick={() => updateQuantity(item.productId, item.quantity - 1)}
                          className="px-3 py-1 text-aura-700 hover:bg-aura-50"
                          aria-label="Decrease quantity"
                        >
                          −
                        </button>
                        <span className="min-w-[2rem] px-2 text-center text-sm font-medium">
                          {item.quantity}
                        </span>
                        <button
                          type="button"
                          onClick={() => updateQuantity(item.productId, item.quantity + 1)}
                          disabled={item.quantity >= item.stock}
                          className="px-3 py-1 text-aura-700 hover:bg-aura-50 disabled:opacity-40"
                          aria-label="Increase quantity"
                        >
                          +
                        </button>
                      </div>
                      <button
                        type="button"
                        onClick={() => removeItem(item.productId)}
                        className="text-sm text-red-600 hover:text-red-800"
                      >
                        Remove
                      </button>
                    </div>
                  </div>
                  <p className="shrink-0 font-semibold text-aura-950">
                    {formatCurrency(parseFloat(item.price) * item.quantity)}
                  </p>
                </li>
              ))}
            </ul>

            <div className="h-fit rounded-2xl border border-aura-200 bg-white p-6 shadow-sm">
              <h2 className="text-lg font-semibold text-aura-950">Order summary</h2>
              <dl className="mt-4 space-y-2 text-sm">
                <div className="flex justify-between">
                  <dt className="text-aura-600">Subtotal</dt>
                  <dd className="font-medium text-aura-950">{formatCurrency(subtotal)}</dd>
                </div>
                {isAuthenticated && user && (
                  <div className="flex justify-between border-t border-aura-100 pt-2">
                    <dt className="text-aura-600">Wallet balance</dt>
                    <dd className="font-medium text-aura-950">{formatCurrency(user.balance)}</dd>
                  </div>
                )}
              </dl>

              {isAuthenticated && subtotal > 0 && !canAfford && (
                <p className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900">
                  Insufficient balance. You need {formatCurrency(subtotal - balance)} more to complete
                  this purchase.
                </p>
              )}

              {!isAuthenticated && (
                <p className="mt-4 text-xs text-aura-600">
                  <Link to="/login" state={{ from: "/cart" }} className="font-semibold text-aura-800">
                    Sign in
                  </Link>{" "}
                  to checkout with your wallet balance.
                </p>
              )}

              <button
                type="button"
                onClick={handleCheckout}
                disabled={checkingOut || items.length === 0}
                className="mt-6 w-full rounded-full bg-aura-950 py-3 text-sm font-semibold text-aura-50 transition hover:bg-aura-800 disabled:opacity-60"
              >
                {checkingOut
                  ? "Processing…"
                  : isAuthenticated
                    ? "Complete checkout"
                    : "Sign in to checkout"}
              </button>
              <p className="mt-3 text-center text-xs text-aura-500">
                Simulated checkout — balance is debited instantly.
              </p>
            </div>
          </div>
        )
      )}
    </div>
  );
}
