// Websites/Codex5.3_HydroFlasked/src/components/profile/ProfileForm.tsx
"use client";

import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import type { SafeUser } from "@/lib/auth/session";
import { UserAvatar } from "@/components/auth/UserAvatar";
import { FormField } from "@/components/ui/FormField";
import { formatPrice } from "@/lib/format";
import { parseApiResponse } from "@/lib/parse-api-response";

type ProfileFormProps = {
  user: SafeUser;
};

export function ProfileForm({ user: initialUser }: ProfileFormProps) {
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [user, setUser] = useState(initialUser);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [showDelete, setShowDelete] = useState(false);
  const [deletePassword, setDeletePassword] = useState("");

  async function handleProfileUpdate(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    setMessage(null);
    setLoading(true);
    try {
      const form = new FormData(e.currentTarget);
      const res = await fetch("/api/profile", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          displayName: form.get("displayName") || null,
          email: form.get("email") || null,
          profileImageUrl: form.get("profileImageUrl") || null,
          currentPassword: form.get("currentPassword") || undefined,
          newPassword: form.get("newPassword") || undefined,
        }),
      });

      const data = await parseApiResponse(res);

      if (!res.ok) {
        setError((data.error as string) ?? "Update failed");
        return;
      }

      setUser(data.user as SafeUser);
      setMessage("Profile updated successfully");
      router.refresh();
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleFileUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    setError(null);
    setMessage(null);
    setLoading(true);
    try {
      const formData = new FormData();
      formData.append("avatar", file);

      const res = await fetch("/api/profile/avatar", {
        method: "POST",
        body: formData,
      });

      const data = await parseApiResponse(res);

      if (!res.ok) {
        setError((data.error as string) ?? "Upload failed");
        return;
      }

      setUser(data.user as SafeUser);
      setMessage("Profile picture updated");
      router.refresh();
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleDeleteAccount() {
    if (!deletePassword) {
      setError("Enter your password to confirm deletion");
      return;
    }

    setError(null);
    setLoading(true);
    try {
      const res = await fetch("/api/profile", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ password: deletePassword }),
      });

      const data = await parseApiResponse(res);

      if (!res.ok) {
        setError((data.error as string) ?? "Could not delete account");
        return;
      }

      router.push("/");
      router.refresh();
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  const displayLabel = user.displayName || user.username;

  return (
    <div className="space-y-10">
      <section className="rounded-2xl border border-white/10 bg-slate-900/60 p-8">
        <div className="flex flex-col items-center gap-4 sm:flex-row sm:items-start">
          <UserAvatar src={user.profileImageUrl} alt={displayLabel} size={96} />
          <div className="flex-1 text-center sm:text-left">
            <h2 className="text-xl font-semibold text-white">{displayLabel}</h2>
            <p className="text-sm text-slate-400">@{user.username}</p>
            <div className="mt-2 flex flex-wrap items-center justify-center gap-2 sm:justify-start">
              <span className="inline-block rounded-full bg-white/10 px-3 py-0.5 text-xs font-medium uppercase tracking-wide text-slate-300">
                {user.role}
              </span>
              <span className="inline-block rounded-full bg-brand-500/20 px-3 py-0.5 text-xs font-medium text-brand-200">
                Balance: {formatPrice(user.balanceCents ?? 0)}
              </span>
            </div>
          </div>
        </div>

        <div className="mt-8 grid gap-6 sm:grid-cols-2">
          <div>
            <p className="text-sm font-medium text-slate-300">Upload image file</p>
            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif"
              onChange={handleFileUpload}
              disabled={loading}
              className="mt-2 w-full text-sm text-slate-400 file:mr-4 file:rounded-full file:border-0 file:bg-brand-500 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-brand-400"
            />
            <p className="mt-1 text-xs text-slate-500">JPEG, PNG, WebP, or GIF — max 2 MB</p>
          </div>
        </div>
      </section>

      {message ? (
        <p className="rounded-lg bg-brand-500/10 px-4 py-3 text-sm text-brand-200" role="status">
          {message}
        </p>
      ) : null}
      {error ? (
        <p className="rounded-lg bg-red-500/10 px-4 py-3 text-sm text-red-300" role="alert">
          {error}
        </p>
      ) : null}

      <section className="rounded-2xl border border-white/10 bg-slate-900/60 p-8">
        <h3 className="text-lg font-semibold text-white">Edit profile</h3>
        <form onSubmit={handleProfileUpdate} className="mt-6 space-y-5">
          <FormField
            label="Display name"
            name="displayName"
            defaultValue={user.displayName ?? ""}
          />
          <FormField
            label="Email"
            name="email"
            type="email"
            defaultValue={user.email ?? ""}
          />
          <FormField
            label="Profile picture URL"
            name="profileImageUrl"
            defaultValue={user.profileImageUrl ?? ""}
            hint="Or upload a file above"
            placeholder="https://example.com/avatar.jpg"
          />
          <div className="border-t border-white/10 pt-6">
            <p className="mb-4 text-sm font-medium text-slate-300">Change password (optional)</p>
            <div className="space-y-5">
              <FormField
                label="Current password"
                name="currentPassword"
                type="password"
                autoComplete="current-password"
              />
              <FormField
                label="New password"
                name="newPassword"
                type="password"
                hint="Leave blank to keep current password"
                autoComplete="new-password"
              />
            </div>
          </div>
          <button
            type="submit"
            disabled={loading}
            className="rounded-full bg-brand-500 px-6 py-2.5 text-sm font-semibold text-white transition hover:bg-brand-400 disabled:opacity-60"
          >
            {loading ? "Saving…" : "Save changes"}
          </button>
        </form>
      </section>

      <section className="rounded-2xl border border-red-500/20 bg-red-950/20 p-8">
        <h3 className="text-lg font-semibold text-red-200">Danger zone</h3>
        <p className="mt-2 text-sm text-slate-400">
          Permanently delete your account and all sessions. This cannot be undone.
        </p>
        {!showDelete ? (
          <button
            type="button"
            onClick={() => setShowDelete(true)}
            className="mt-4 rounded-full border border-red-500/40 px-5 py-2 text-sm font-medium text-red-300 transition hover:bg-red-500/10"
          >
            Delete my account
          </button>
        ) : (
          <div className="mt-4 space-y-4">
            <label className="block">
              <span className="text-sm font-medium text-slate-300">
                Confirm with your password
              </span>
              <input
                type="password"
                value={deletePassword}
                onChange={(e) => setDeletePassword(e.target.value)}
                className="mt-1.5 w-full max-w-sm rounded-lg border border-white/15 bg-slate-900/80 px-4 py-2.5 text-white focus:border-red-500 focus:outline-none"
              />
            </label>
            <div className="flex gap-3">
              <button
                type="button"
                onClick={handleDeleteAccount}
                disabled={loading}
                className="rounded-full bg-red-600 px-5 py-2 text-sm font-semibold text-white hover:bg-red-500 disabled:opacity-60"
              >
                Confirm deletion
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowDelete(false);
                  setDeletePassword("");
                }}
                className="rounded-full border border-white/20 px-5 py-2 text-sm text-slate-300 hover:text-white"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
      </section>
    </div>
  );
}

// Websites/Opus_NovaNest/src/components/solid/ProfileForm.tsx
import { createSignal, Show, onMount } from 'solid-js';
import { formatPrice } from '../../lib/format';

interface User {
  id: number;
  username: string;
  email: string;
  displayName: string;
  avatarUrl: string | null;
  role: string;
  balanceCents: number;
  createdAt: string;
  updatedAt: string;
}

interface Props {
  initialUser: User;
  forbidden?: boolean;
}

export default function ProfileForm(props: Props) {
  const [user, setUser] = createSignal<User>(props.initialUser);
  const [message, setMessage] = createSignal<{ type: 'ok' | 'err'; text: string } | null>(
    props.forbidden ? { type: 'err', text: 'You do not have permission to access the admin area.' } : null,
  );
  const [loading, setLoading] = createSignal(false);

  const [email, setEmail] = createSignal(props.initialUser.email);
  const [displayName, setDisplayName] = createSignal(props.initialUser.displayName);
  const [avatarUrl, setAvatarUrl] = createSignal(props.initialUser.avatarUrl ?? '');
  const [currentPassword, setCurrentPassword] = createSignal('');
  const [newPassword, setNewPassword] = createSignal('');
  const [deletePassword, setDeletePassword] = createSignal('');

  onMount(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('error') === 'forbidden' && !props.forbidden) {
      setMessage({ type: 'err', text: 'You do not have permission to access the admin area.' });
    }
  });

  async function saveProfile(e: Event) {
    e.preventDefault();
    setLoading(true);
    setMessage(null);
    try {
      const res = await fetch('/api/profile', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: email(),
          displayName: displayName(),
          avatarUrl: avatarUrl().trim() || null,
          currentPassword: currentPassword() || undefined,
          newPassword: newPassword() || undefined,
        }),
      });
      const json = await res.json();
      if (!res.ok) {
        setMessage({ type: 'err', text: json.error ?? 'Update failed.' });
        return;
      }
      setUser(json.user);
      setCurrentPassword('');
      setNewPassword('');
      setMessage({ type: 'ok', text: 'Profile updated successfully.' });
    } catch {
      setMessage({ type: 'err', text: 'Network error.' });
    } finally {
      setLoading(false);
    }
  }

  async function uploadAvatar(e: Event) {
    e.preventDefault();
    const input = document.getElementById('avatar-file') as HTMLInputElement;
    const file = input?.files?.[0];
    if (!file) {
      setMessage({ type: 'err', text: 'Choose an image file first.' });
      return;
    }
    setLoading(true);
    setMessage(null);
    const formData = new FormData();
    formData.append('avatar', file);
    try {
      const res = await fetch('/api/profile/avatar', { method: 'POST', body: formData });
      const json = await res.json();
      if (!res.ok) {
        setMessage({ type: 'err', text: json.error ?? 'Upload failed.' });
        return;
      }
      setUser(json.user);
      setAvatarUrl(json.user.avatarUrl ?? '');
      input.value = '';
      setMessage({ type: 'ok', text: 'Profile picture uploaded.' });
    } catch {
      setMessage({ type: 'err', text: 'Network error.' });
    } finally {
      setLoading(false);
    }
  }

  async function deleteAccount(e: Event) {
    e.preventDefault();
    if (!confirm('Delete your account permanently? This cannot be undone.')) return;
    if (!deletePassword()) {
      setMessage({ type: 'err', text: 'Enter your password to confirm deletion.' });
      return;
    }
    setLoading(true);
    setMessage(null);
    try {
      const res = await fetch('/api/profile', {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ password: deletePassword() }),
      });
      const json = await res.json();
      if (!res.ok) {
        setMessage({ type: 'err', text: json.error ?? 'Deletion failed.' });
        return;
      }
      window.location.href = '/';
    } catch {
      setMessage({ type: 'err', text: 'Network error.' });
    } finally {
      setLoading(false);
    }
  }

  async function logout() {
    await fetch('/api/auth/logout', { method: 'POST' });
    window.location.href = '/';
  }

  const avatarSrc = () => user().avatarUrl;

  return (
    <div class="space-y-10">
      <Show when={message()}>
        {(m) => (
          <p
            class={`rounded-lg border px-4 py-3 text-sm ${
              m().type === 'ok'
                ? 'border-accent/40 bg-accent/10 text-accent'
                : 'border-red-500/40 bg-red-500/10 text-red-300'
            }`}
            role="alert"
          >
            {m().text}
          </p>
        )}
      </Show>

      <section class="flex flex-col items-center gap-4 sm:flex-row sm:items-start">
        <Show
          when={avatarSrc()}
          fallback={
            <span class="flex h-24 w-24 shrink-0 items-center justify-center rounded-full bg-nest-800 text-3xl font-semibold text-accent ring-2 ring-white/10">
              {user().displayName.charAt(0).toUpperCase()}
            </span>
          }
        >
          <img
            src={avatarSrc()!}
            alt=""
            class="h-24 w-24 shrink-0 rounded-full object-cover ring-2 ring-white/10"
            width="96"
            height="96"
          />
        </Show>
        <div class="text-center sm:text-left">
          <h1 class="font-display text-2xl font-semibold text-white">{user().displayName}</h1>
          <p class="text-nest-100/60">@{user().username}</p>
          <p class="mt-1 text-xs uppercase tracking-wide text-accent/80">{user().role}</p>
          <p class="mt-2 text-sm text-nest-100/70">
            Account balance:{' '}
            <span class="font-medium text-accent">{formatPrice(user().balanceCents)}</span>
          </p>
        </div>
      </section>

      <form onSubmit={uploadAvatar} class="rounded-2xl border border-white/10 bg-nest-900/50 p-6">
        <h2 class="font-display text-lg font-semibold text-white">Profile picture</h2>
        <p class="mt-1 text-sm text-nest-100/60">
          Upload an image (JPEG, PNG, WebP, GIF — max 2 MB) or set a URL in the form below.
        </p>
        <div class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end">
          <input
            id="avatar-file"
            name="avatar"
            type="file"
            accept="image/jpeg,image/png,image/webp,image/gif"
            class="block w-full text-sm text-nest-100/70 file:mr-4 file:rounded-lg file:border-0 file:bg-accent file:px-4 file:py-2 file:text-sm file:font-medium file:text-nest-950"
          />
          <button
            type="submit"
            disabled={loading()}
            class="shrink-0 rounded-lg border border-accent/40 px-4 py-2 text-sm font-medium text-accent hover:bg-accent/10 disabled:opacity-50"
          >
            Upload image
          </button>
        </div>
      </form>

      <form onSubmit={saveProfile} class="rounded-2xl border border-white/10 bg-nest-900/50 p-6 space-y-5">
        <h2 class="font-display text-lg font-semibold text-white">Profile details</h2>

        <div>
          <label class="mb-1.5 block text-sm text-nest-100/70">Username</label>
          <input
            type="text"
            value={user().username}
            disabled
            class="w-full cursor-not-allowed rounded-lg border border-white/10 bg-nest-950/50 px-4 py-2.5 text-nest-100/50"
          />
          <p class="mt-1 text-xs text-nest-100/40">Username cannot be changed.</p>
        </div>

        <div>
          <label class="mb-1.5 block text-sm text-nest-100/70" for="displayName">
            Display name
          </label>
          <input
            id="displayName"
            type="text"
            required
            value={displayName()}
            onInput={(e) => setDisplayName(e.currentTarget.value)}
            class="w-full rounded-lg border border-white/15 bg-nest-950 px-4 py-2.5 text-white focus:border-accent focus:outline-none"
          />
        </div>

        <div>
          <label class="mb-1.5 block text-sm text-nest-100/70" for="email">
            Email
          </label>
          <input
            id="email"
            type="email"
            required
            value={email()}
            onInput={(e) => setEmail(e.currentTarget.value)}
            class="w-full rounded-lg border border-white/15 bg-nest-950 px-4 py-2.5 text-white focus:border-accent focus:outline-none"
          />
        </div>

        <div>
          <label class="mb-1.5 block text-sm text-nest-100/70" for="avatarUrl">
            Profile picture URL
          </label>
          <input
            id="avatarUrl"
            type="url"
            value={avatarUrl()}
            onInput={(e) => setAvatarUrl(e.currentTarget.value)}
            placeholder="https://… or leave empty"
            class="w-full rounded-lg border border-white/15 bg-nest-950 px-4 py-2.5 text-white focus:border-accent focus:outline-none"
          />
        </div>

        <div class="border-t border-white/10 pt-5">
          <h3 class="text-sm font-medium text-white">Change password</h3>
          <p class="mt-1 text-xs text-nest-100/50">Leave blank to keep your current password.</p>
          <div class="mt-4 grid gap-4 sm:grid-cols-2">
            <div>
              <label class="mb-1.5 block text-sm text-nest-100/70" for="currentPassword">
                Current password
              </label>
              <input
                id="currentPassword"
                type="password"
                value={currentPassword()}
                onInput={(e) => setCurrentPassword(e.currentTarget.value)}
                class="w-full rounded-lg border border-white/15 bg-nest-950 px-4 py-2.5 text-white focus:border-accent focus:outline-none"
              />
            </div>
            <div>
              <label class="mb-1.5 block text-sm text-nest-100/70" for="newPassword">
                New password
              </label>
              <input
                id="newPassword"
                type="password"
                minLength={8}
                value={newPassword()}
                onInput={(e) => setNewPassword(e.currentTarget.value)}
                class="w-full rounded-lg border border-white/15 bg-nest-950 px-4 py-2.5 text-white focus:border-accent focus:outline-none"
              />
            </div>
          </div>
        </div>

        <button
          type="submit"
          disabled={loading()}
          class="rounded-lg bg-accent px-6 py-2.5 text-sm font-semibold text-nest-950 hover:bg-accent/90 disabled:opacity-50"
        >
          Save changes
        </button>
      </form>

      <div class="flex flex-wrap gap-4">
        <button
          type="button"
          onClick={logout}
          class="rounded-lg border border-white/20 px-4 py-2 text-sm text-nest-100/80 hover:border-white/40"
        >
          Log out
        </button>
      </div>

      <form
        onSubmit={deleteAccount}
        class="rounded-2xl border border-red-500/30 bg-red-500/5 p-6 space-y-4"
      >
        <h2 class="font-display text-lg font-semibold text-red-300">Delete account</h2>
        <p class="text-sm text-nest-100/60">
          Permanently remove your account and all sessions. This action cannot be undone.
        </p>
        <div>
          <label class="mb-1.5 block text-sm text-nest-100/70" for="deletePassword">
            Confirm with your password
          </label>
          <input
            id="deletePassword"
            type="password"
            required
            value={deletePassword()}
            onInput={(e) => setDeletePassword(e.currentTarget.value)}
            class="w-full max-w-md rounded-lg border border-red-500/30 bg-nest-950 px-4 py-2.5 text-white focus:border-red-400 focus:outline-none"
          />
        </div>
        <button
          type="submit"
          disabled={loading()}
          class="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-500 disabled:opacity-50"
        >
          Delete my account
        </button>
      </form>
    </div>
  );
}
