// Websites/Codex5.3_HydroFlasked/src/components/cart/AddToCartButton.tsx
"use client";

import { useState } from "react";
import { useCart } from "@/context/CartContext";

type AddToCartButtonProps = {
  productId: string;
  disabled?: boolean;
};

export function AddToCartButton({ productId, disabled }: AddToCartButtonProps) {
  const { addItem } = useCart();
  const [added, setAdded] = useState(false);

  function handleClick() {
    addItem(productId);
    setAdded(true);
    setTimeout(() => setAdded(false), 1500);
  }

  return (
    <button
      type="button"
      onClick={handleClick}
      disabled={disabled}
      className="mt-4 w-full rounded-full border border-brand-500/50 bg-brand-500/10 py-2 text-sm font-semibold text-brand-300 transition hover:bg-brand-500/20 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"
    >
      {disabled ? "Out of stock" : added ? "Added ✓" : "Add to cart"}
    </button>
  );
}

// Génération_Code_Application/Opus_NovaNest/src/components/solid/AddToCartButton.tsx
import { createSignal } from 'solid-js';
import { addToCart } from '../../stores/cart';

interface Props {
  productId: number;
  name: string;
  priceCents: number;
}

export default function AddToCartButton(props: Props) {
  const [added, setAdded] = createSignal(false);

  const handleClick = () => {
    const ok = addToCart({
      productId: Number(props.productId),
      name: String(props.name),
      priceCents: Number(props.priceCents),
    });

    if (ok) {
      setAdded(true);
      window.setTimeout(() => setAdded(false), 2000);
    }
  };

  return (
    <button
      type="button"
      onClick={handleClick}
      class="w-full rounded-lg border border-accent/40 bg-accent/10 px-4 py-2 text-sm font-medium text-accent transition hover:bg-accent hover:text-nest-950"
    >
      {added() ? 'Added to cart ✓' : 'Add to cart'}
    </button>
  );
}
