// Websites/GPT5.5_VoltStream/frontend/src/components/AdminSystemLogs.tsx
import { useCallback, useEffect, useState } from "react";
import { fetchAdminLogs, type SystemLog, type SystemLogQuery } from "../api/admin";

const EVENT_LABELS: Record<string, string> = {
  "auth.login.success": "Login success",
  "auth.login.failure": "Login failure",
  "auth.register.success": "Register success",
  "auth.register.failure": "Register failure",
  "profile.update": "Profile update",
  "transaction.checkout.success": "Checkout success",
  "transaction.checkout.failure": "Checkout failure",
};

function eventLabel(type: string): string {
  return EVENT_LABELS[type] ?? type;
}

function severityClass(severity: string, success: boolean): string {
  if (!success || severity === "error") return "text-amber-400 bg-amber-400/10";
  if (severity === "warning") return "text-yellow-300 bg-yellow-400/10";
  return "text-emerald-400 bg-emerald-400/10";
}

export default function AdminSystemLogs() {
  const [logs, setLogs] = useState<SystemLog[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filters, setFilters] = useState<SystemLogQuery>({ limit: 50, offset: 0 });

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchAdminLogs(filters);
      setLogs(data.items);
      setTotal(data.total);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load logs");
    } finally {
      setLoading(false);
    }
  }, [filters]);

  useEffect(() => {
    load();
  }, [load]);

  const page = Math.floor((filters.offset ?? 0) / (filters.limit ?? 50));
  const pageSize = filters.limit ?? 50;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  return (
    <div className="mt-8">
      <div className="flex flex-wrap items-end gap-4 rounded-2xl border border-grid-border bg-grid-surface/60 p-4">
        <label className="text-sm text-grid-muted">
          Event type
          <select
            value={filters.event_type ?? ""}
            onChange={(e) =>
              setFilters((f) => ({
                ...f,
                event_type: e.target.value || undefined,
                offset: 0,
              }))
            }
            className="mt-1 block rounded-lg border border-grid-border bg-grid-dark px-3 py-2 text-white"
          >
            <option value="">All events</option>
            {Object.entries(EVENT_LABELS).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
        </label>
        <label className="text-sm text-grid-muted">
          Severity
          <select
            value={filters.severity ?? ""}
            onChange={(e) =>
              setFilters((f) => ({
                ...f,
                severity: e.target.value || undefined,
                offset: 0,
              }))
            }
            className="mt-1 block rounded-lg border border-grid-border bg-grid-dark px-3 py-2 text-white"
          >
            <option value="">All</option>
            <option value="info">Info</option>
            <option value="warning">Warning</option>
            <option value="error">Error</option>
          </select>
        </label>
        <button
          type="button"
          onClick={load}
          className="rounded-lg border border-grid-border px-4 py-2 text-sm font-medium text-white hover:border-grid-cyan/50"
        >
          Refresh
        </button>
        <p className="ml-auto text-sm text-grid-muted">
          {total} event{total !== 1 ? "s" : ""} total
        </p>
      </div>

      {error && <p className="mt-4 text-sm text-amber-400">{error}</p>}
      {loading && <p className="mt-8 text-grid-muted">Loading system logs…</p>}

      {!loading && logs.length === 0 && (
        <p className="mt-8 text-center text-grid-muted">No log entries match your filters.</p>
      )}

      {!loading && logs.length > 0 && (
        <div className="mt-6 overflow-x-auto rounded-2xl border border-grid-border">
          <table className="w-full min-w-[900px] text-left text-sm">
            <thead className="border-b border-grid-border bg-grid-surface/80 text-grid-muted">
              <tr>
                <th className="px-4 py-3">Time</th>
                <th className="px-4 py-3">Event</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Message</th>
                <th className="px-4 py-3">Actor</th>
                <th className="px-4 py-3">IP</th>
                <th className="px-4 py-3">Details</th>
              </tr>
            </thead>
            <tbody>
              {logs.map((log) => (
                <tr key={log.id} className="border-b border-grid-border/50 hover:bg-grid-surface/40 align-top">
                  <td className="whitespace-nowrap px-4 py-3 text-grid-muted">
                    {new Date(log.created_at).toLocaleString()}
                  </td>
                  <td className="px-4 py-3 text-white">{eventLabel(log.event_type)}</td>
                  <td className="px-4 py-3">
                    <span
                      className={`rounded px-2 py-0.5 text-xs font-semibold uppercase ${severityClass(
                        log.severity,
                        log.success
                      )}`}
                    >
                      {log.success ? log.severity : "failed"}
                    </span>
                  </td>
                  <td className="max-w-xs px-4 py-3 text-grid-muted">{log.message}</td>
                  <td className="px-4 py-3 text-grid-muted">
                    {log.actor_email ?? (log.actor_user_id ? `#${log.actor_user_id}` : "—")}
                    {log.target_user_id != null && log.target_user_id !== log.actor_user_id && (
                      <span className="block text-xs">→ user #{log.target_user_id}</span>
                    )}
                  </td>
                  <td className="px-4 py-3 font-mono text-xs text-grid-muted">{log.ip_address ?? "—"}</td>
                  <td className="max-w-[200px] px-4 py-3">
                    {log.details ? (
                      <pre className="overflow-x-auto text-xs text-grid-muted">
                        {JSON.stringify(log.details, null, 0)}
                      </pre>
                    ) : (
                      "—"
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {totalPages > 1 && (
        <div className="mt-6 flex items-center justify-center gap-4">
          <button
            type="button"
            disabled={page === 0}
            onClick={() => setFilters((f) => ({ ...f, offset: Math.max(0, (f.offset ?? 0) - pageSize) }))}
            className="rounded-lg border border-grid-border px-3 py-1.5 text-sm disabled:opacity-40"
          >
            Previous
          </button>
          <span className="text-sm text-grid-muted">
            Page {page + 1} of {totalPages}
          </span>
          <button
            type="button"
            disabled={page + 1 >= totalPages}
            onClick={() => setFilters((f) => ({ ...f, offset: (f.offset ?? 0) + pageSize }))}
            className="rounded-lg border border-grid-border px-3 py-1.5 text-sm disabled:opacity-40"
          >
            Next
          </button>
        </div>
      )}
    </div>
  );
}

// Websites/Sonnet_4.6_Solace_Ground/src/components/solid/AdminSystemLogs.tsx
import { createSignal, createEffect, Show, For } from 'solid-js';
import type { PublicSystemLog } from '@/lib/monitoring/types';

const inputClass =
  'mt-1 w-full rounded-lg border border-cork-300 bg-white px-3 py-2 text-sm text-cork-900 focus:border-cork-600 focus:outline-none focus:ring-1 focus:ring-cork-600';

const severityClass: Record<string, string> = {
  info: 'bg-cork-100 text-cork-700',
  warning: 'bg-amber-100 text-amber-800',
  error: 'bg-red-100 text-red-800',
};

const statusClass: Record<string, string> = {
  success: 'text-sage-600',
  failure: 'text-red-700',
};

export default function AdminSystemLogs() {
  const [logs, setLogs] = createSignal<PublicSystemLog[]>([]);
  const [total, setTotal] = createSignal(0);
  const [category, setCategory] = createSignal('all');
  const [status, setStatus] = createSignal('all');
  const [action, setAction] = createSignal('');
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal('');
  const [expandedId, setExpandedId] = createSignal<number | null>(null);

  async function load() {
    setLoading(true);
    setError('');
    const params = new URLSearchParams({ limit: '100', offset: '0' });
    if (category() !== 'all') params.set('category', category());
    if (status() !== 'all') params.set('status', status());
    if (action().trim()) params.set('action', action().trim());

    try {
      const res = await fetch(`/api/admin/logs?${params}`, {
        credentials: 'same-origin',
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? 'Failed to load logs.');
        return;
      }
      setLogs(data.logs ?? []);
      setTotal(data.total ?? 0);
    } catch {
      setError('Could not load system logs.');
    } finally {
      setLoading(false);
    }
  }

  createEffect(() => {
    category();
    status();
    action();
    load();
  });

  return (
    <div class="space-y-6">
      <p class="text-sm text-cork-600">
        Internal audit trail for authentication, profile changes, checkout transactions, and admin actions.
      </p>

      <form
        class="rounded-2xl border border-cork-200 bg-cork-50/60 p-5"
        onSubmit={(e) => {
          e.preventDefault();
          load();
        }}
      >
        <div class="grid gap-4 sm:grid-cols-3">
          <div>
            <label for="log-category" class="text-xs font-medium text-cork-700">
              Category
            </label>
            <select
              id="log-category"
              class={inputClass}
              value={category()}
              onChange={(e) => setCategory(e.currentTarget.value)}
            >
              <option value="all">All</option>
              <option value="auth">Auth</option>
              <option value="profile">Profile</option>
              <option value="transaction">Transaction</option>
              <option value="admin">Admin</option>
              <option value="review">Review</option>
            </select>
          </div>
          <div>
            <label for="log-status" class="text-xs font-medium text-cork-700">
              Status
            </label>
            <select
              id="log-status"
              class={inputClass}
              value={status()}
              onChange={(e) => setStatus(e.currentTarget.value)}
            >
              <option value="all">All</option>
              <option value="success">Success</option>
              <option value="failure">Failure</option>
            </select>
          </div>
          <div>
            <label for="log-action" class="text-xs font-medium text-cork-700">
              Action contains
            </label>
            <input
              id="log-action"
              type="search"
              placeholder="e.g. login, checkout"
              class={inputClass}
              value={action()}
              onInput={(e) => setAction(e.currentTarget.value)}
            />
          </div>
        </div>
      </form>

      <Show when={loading()}>
        <p class="text-sm text-cork-500">Loading events…</p>
      </Show>

      <Show when={error()}>
        <p class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error()}</p>
      </Show>

      <Show when={!loading() && !error()}>
        <p class="text-xs text-cork-500">
          Showing {logs().length} of {total()} events (newest first)
        </p>

        <div class="overflow-x-auto rounded-2xl border border-cork-200 bg-white">
          <table class="w-full min-w-[720px] text-left text-sm">
            <thead class="border-b border-cork-200 bg-cork-50">
              <tr>
                <th class="px-4 py-3 font-medium">Time</th>
                <th class="px-4 py-3 font-medium">Action</th>
                <th class="px-4 py-3 font-medium">User</th>
                <th class="px-4 py-3 font-medium">Severity</th>
                <th class="px-4 py-3 font-medium">Status</th>
                <th class="px-4 py-3 font-medium" />
              </tr>
            </thead>
            <tbody>
              <For each={logs()}>
                {(log) => (
                  <>
                    <tr class="border-b border-cork-100 hover:bg-cork-50/50">
                      <td class="whitespace-nowrap px-4 py-3 text-cork-600">
                        {new Date(log.createdAt).toLocaleString()}
                      </td>
                      <td class="px-4 py-3">
                        <span class="font-mono text-xs text-cork-800">{log.action}</span>
                        <p class="mt-0.5 max-w-xs truncate text-cork-600">{log.message}</p>
                      </td>
                      <td class="px-4 py-3 text-cork-700">
                        {log.username ?? '—'}
                      </td>
                      <td class="px-4 py-3">
                        <span
                          class={`inline-block rounded-full px-2 py-0.5 text-xs font-medium capitalize ${severityClass[log.severity] ?? ''}`}
                        >
                          {log.severity}
                        </span>
                      </td>
                      <td class={`px-4 py-3 font-medium capitalize ${statusClass[log.status] ?? ''}`}>
                        {log.status}
                      </td>
                      <td class="px-4 py-3 text-right">
                        <button
                          type="button"
                          class="text-xs font-medium text-cork-800 hover:underline"
                          onClick={() =>
                            setExpandedId(expandedId() === log.id ? null : log.id)
                          }
                        >
                          {expandedId() === log.id ? 'Hide' : 'Details'}
                        </button>
                      </td>
                    </tr>
                    <Show when={expandedId() === log.id}>
                      <tr class="border-b border-cork-100 bg-cork-50/80">
                        <td colspan="6" class="px-4 py-3 text-xs text-cork-600">
                          <dl class="grid gap-2 sm:grid-cols-2">
                            <div>
                              <dt class="font-medium text-cork-800">IP</dt>
                              <dd>{log.ipAddress ?? '—'}</dd>
                            </div>
                            <div>
                              <dt class="font-medium text-cork-800">User agent</dt>
                              <dd class="break-all">{log.userAgent ?? '—'}</dd>
                            </div>
                            <div class="sm:col-span-2">
                              <dt class="font-medium text-cork-800">Metadata</dt>
                              <dd>
                                <pre class="mt-1 overflow-x-auto rounded bg-white p-2 text-[11px]">
                                  {JSON.stringify(log.metadata ?? {}, null, 2)}
                                </pre>
                              </dd>
                            </div>
                          </dl>
                        </td>
                      </tr>
                    </Show>
                  </>
                )}
              </For>
            </tbody>
          </table>
        </div>

        <Show when={logs().length === 0}>
          <p class="py-8 text-center text-sm text-cork-500">No events match your filters.</p>
        </Show>
      </Show>
    </div>
  );
}
