// Websites/GPT5.5_GamerGrid/src/components/solid/CartPage.tsx
import { Show, createSignal, onCleanup, onMount } from 'solid-js';
import {
  clearCart,
  getProductIds,
  removeFromCart,
  subscribe,
  type CartItem,
} from '@/lib/cart';

interface Props {
  isLoggedIn: boolean;
  initialBalance: number | null;
}

export default function CartPage(props: Props) {
  const [items, setItems] = createSignal<CartItem[]>([]);
  const [total, setTotal] = createSignal(0);
  const [balance, setBalance] = createSignal(props.initialBalance);
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [success, setSuccess] = createSignal<string | null>(null);
  const [orderDetails, setOrderDetails] = createSignal<{
    total: number;
    newBalance: number;
    orderId: string;
    invoiceNumber: string;
  } | null>(null);

  onMount(() => {
    const unsubscribe = subscribe((snap) => {
      setItems(snap.items);
      setTotal(snap.total);
    });
    onCleanup(unsubscribe);
  });

  const canCheckout = () =>
    props.isLoggedIn && items().length > 0 && balance() !== null;

  const hasEnoughBalance = () => {
    const b = balance();
    return b !== null && b >= total();
  };

  const handleCheckout = async () => {
    if (!props.isLoggedIn) return;
    setError(null);
    setSuccess(null);
    setOrderDetails(null);
    setLoading(true);

    try {
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ productIds: getProductIds() }),
      });
      const json = await res.json();

      if (!res.ok) {
        setError(json.error ?? 'Checkout failed.');
        return;
      }

      setBalance(json.newBalance);
      setSuccess(json.message);
      setOrderDetails({
        total: json.total,
        newBalance: json.newBalance,
        orderId: json.orderId,
        invoiceNumber: json.invoiceNumber,
      });
      clearCart();
    } catch {
      setError('Network error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="space-y-8">
      <Show when={success()}>
        <div
          class="rounded-2xl border border-stream-500/30 bg-stream-500/10 p-6"
          role="status"
        >
          <p class="font-semibold text-stream-300">{success()}</p>
          <Show when={orderDetails()}>
            {(order) => (
              <>
                <p class="mt-2 text-sm text-slate-400">
                  Charged ${order().total.toFixed(2)} · New balance:{' '}
                  <span class="font-mono text-white">
                    ${order().newBalance.toFixed(2)}
                  </span>
                </p>
                <p class="mt-1 font-mono text-xs text-slate-500">
                  Invoice {order().invoiceNumber}
                </p>
                <a
                  href={`/api/invoices/${order().orderId}`}
                  download={`VoltStream-Invoice-${order().invoiceNumber}.pdf`}
                  class="mt-4 inline-flex items-center gap-2 rounded-full bg-volt-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-volt-500 transition-colors"
                >
                  Download invoice (PDF)
                </a>
              </>
            )}
          </Show>
          <a
            href="/"
            class="mt-4 inline-flex text-sm font-medium text-volt-400 hover:text-volt-300"
          >
            Continue shopping →
          </a>
        </div>
      </Show>

      <Show when={error()}>
        <p
          class="rounded-lg border border-red-500/30 bg-red-950/40 px-4 py-3 text-sm text-red-200"
          role="alert"
        >
          {error()}
        </p>
      </Show>

      <Show
        when={items().length > 0}
        fallback={
          <div class="rounded-2xl border border-white/10 bg-slate-900/50 p-10 text-center">
            <p class="text-lg font-medium text-white">Your cart is empty</p>
            <p class="mt-2 text-sm text-slate-400">
              Browse our catalog and add products to get started.
            </p>
            <a
              href="/#products"
              class="mt-6 inline-flex rounded-full bg-volt-600 px-6 py-3 text-sm font-semibold text-white hover:bg-volt-500"
            >
              View products
            </a>
          </div>
        }
      >
        <div class="overflow-hidden rounded-2xl border border-white/10 bg-slate-900/50">
          <ul class="divide-y divide-white/5">
            {items().map((item) => (
              <li class="flex flex-col gap-4 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6">
                <div>
                  <p class="font-medium text-white">{item.name}</p>
                  <p class="mt-1 font-mono text-sm text-slate-400">
                    ${item.price.toFixed(2)} each
                  </p>
                </div>
                <div class="flex items-center gap-4">
                  <p class="font-mono text-lg font-semibold text-white">
                    ${item.price.toFixed(2)}
                  </p>
                  <button
                    type="button"
                    onClick={() => removeFromCart(item.id)}
                    class="text-sm text-red-400 hover:text-red-300"
                  >
                    Remove
                  </button>
                </div>
              </li>
            ))}
          </ul>
        </div>

        <aside class="rounded-2xl border border-volt-500/20 bg-gradient-to-br from-volt-950/50 to-slate-900/80 p-6">
          <h2 class="text-lg font-semibold text-white">Order summary</h2>
          <dl class="mt-4 space-y-3 text-sm">
            <div class="flex justify-between text-slate-400">
              <dt>Items</dt>
              <dd>{items().length}</dd>
            </div>
            <div class="flex justify-between text-slate-400">
              <dt>Subtotal</dt>
              <dd class="font-mono text-white">${total().toFixed(2)}</dd>
            </div>
            <Show when={props.isLoggedIn && balance() !== null}>
              <div class="flex justify-between border-t border-white/10 pt-3">
                <dt class="text-slate-400">Account balance</dt>
                <dd class="font-mono font-medium text-stream-400">
                  ${balance()!.toFixed(2)}
                </dd>
              </div>
            </Show>
            <div class="flex justify-between border-t border-white/10 pt-3 text-base">
              <dt class="font-semibold text-white">Total due</dt>
              <dd class="font-mono text-xl font-bold text-white">
                ${total().toFixed(2)}
              </dd>
            </div>
          </dl>

          <Show when={!props.isLoggedIn}>
            <p class="mt-4 rounded-lg border border-amber-500/30 bg-amber-950/30 px-4 py-3 text-sm text-amber-200">
              <a href="/login?redirect=/cart" class="font-medium text-amber-100 underline">
                Sign in
              </a>{' '}
              to complete checkout. Payment is deducted from your account balance.
            </p>
          </Show>

          <Show when={props.isLoggedIn && balance() !== null && !hasEnoughBalance()}>
            <p class="mt-4 rounded-lg border border-red-500/30 bg-red-950/30 px-4 py-3 text-sm text-red-200">
              Insufficient balance. You need ${total().toFixed(2)} but have $
              {balance()!.toFixed(2)}.
            </p>
          </Show>

          <button
            type="button"
            disabled={!canCheckout() || loading() || !hasEnoughBalance()}
            onClick={handleCheckout}
            class="mt-6 w-full rounded-full bg-volt-600 py-3 text-sm font-semibold text-white hover:bg-volt-500 disabled:cursor-not-allowed disabled:opacity-50 transition-colors"
          >
            {loading()
              ? 'Processing…'
              : `Complete checkout — $${total().toFixed(2)}`}
          </button>
          <p class="mt-3 text-center text-xs text-slate-500">
            Simulated checkout · balance updated on success
          </p>
        </aside>
      </Show>
    </div>
  );
}

// Génération_Code_Application/Composer2.5_SproutSoil/frontend/src/pages/CartPage.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { checkoutApi, formatMoney, invoiceApi } from "../api/client";
import { useAuth } from "../context/AuthContext";
import { useCart } from "../context/CartContext";

export default function CartPage() {
  const { items, subtotal, itemCount, updateQuantity, removeFromCart, clearCart } =
    useCart();
  const { user, updateUser } = useAuth();
  const navigate = useNavigate();

  const [checkingOut, setCheckingOut] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [invoiceNumber, setInvoiceNumber] = useState(null);
  const [downloading, setDownloading] = useState(false);

  const handleCheckout = async () => {
    if (!user) {
      navigate("/login", { state: { from: "/cart" } });
      return;
    }

    if (items.length === 0) return;

    setCheckingOut(true);
    setError("");
    setSuccess("");

    try {
      const result = await checkoutApi.placeOrder({
        items: items.map((i) => ({
          product_id: i.productId,
          quantity: i.quantity,
        })),
      });
      updateUser(result.user);
      clearCart();
      setInvoiceNumber(result.invoice_number);
      setSuccess(
        `${result.message} Total charged: ${formatMoney(result.total)}. ` +
          `New balance: ${formatMoney(result.new_balance)}. ` +
          `Invoice: ${result.invoice_number}.`
      );
    } catch (err) {
      setError(err.message);
    } finally {
      setCheckingOut(false);
    }
  };

  if (items.length === 0 && !success) {
    return (
      <div className="mx-auto max-w-2xl px-6 py-20 text-center">
        <p className="text-5xl">🛒</p>
        <h1 className="mt-4 font-display text-3xl font-bold text-soil-950">
          Your cart is empty
        </h1>
        <p className="mt-2 text-soil-600">
          Browse our indoor gardening essentials and add something you love.
        </p>
        <Link
          to="/#products"
          className="mt-8 inline-block rounded-full bg-sprout-500 px-8 py-3 text-sm font-semibold text-white hover:bg-sprout-600"
        >
          Shop products
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-6 py-12">
      <h1 className="font-display text-3xl font-bold text-soil-950">
        Shopping cart
      </h1>
      <p className="mt-2 text-soil-600">
        {itemCount} {itemCount === 1 ? "item" : "items"} in your cart
      </p>

      {success && (
        <div className="mt-6 rounded-2xl bg-sprout-500/10 px-5 py-4 ring-1 ring-sprout-500/20">
          <p className="font-medium text-sprout-800">Order complete</p>
          <p className="mt-1 text-sm text-sprout-700">{success}</p>
          <div className="mt-4 flex flex-wrap gap-3">
            {invoiceNumber && (
              <button
                type="button"
                disabled={downloading}
                onClick={async () => {
                  setDownloading(true);
                  try {
                    await invoiceApi.downloadPdf(invoiceNumber);
                  } catch (err) {
                    setError(err.message);
                  } finally {
                    setDownloading(false);
                  }
                }}
                className="rounded-full bg-soil-800 px-5 py-2 text-sm font-medium text-white hover:bg-soil-700 disabled:opacity-60"
              >
                {downloading ? "Downloading…" : "Download invoice (PDF)"}
              </button>
            )}
            <Link
              to="/catalog"
              className="inline-flex items-center rounded-full border border-soil-200 px-5 py-2 text-sm font-medium text-soil-700 hover:bg-soil-100"
            >
              Continue shopping
            </Link>
          </div>
        </div>
      )}

      {error && (
        <p className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700 ring-1 ring-red-200">
          {error}
        </p>
      )}

      {items.length > 0 && (
        <div className="mt-8 grid gap-8 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-4">
            {items.map((item) => (
              <article
                key={item.productId}
                className="flex gap-4 rounded-2xl border border-soil-200 bg-white p-4"
              >
                <div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-soil-100">
                  {item.image_url ? (
                    <img
                      src={item.image_url}
                      alt=""
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <span className="flex h-full w-full items-center justify-center text-2xl">
                      🌿
                    </span>
                  )}
                </div>

                <div className="flex flex-1 flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                  <div>
                    <h2 className="font-medium text-soil-900">{item.name}</h2>
                    <p className="text-sm text-soil-500">
                      {formatMoney(item.price)} each
                    </p>
                  </div>

                  <div className="flex items-center gap-3">
                    <div className="flex items-center rounded-lg border border-soil-200">
                      <button
                        type="button"
                        onClick={() => updateQuantity(item.productId, item.quantity - 1)}
                        className="px-3 py-1.5 text-soil-600 hover:bg-soil-50"
                        aria-label="Decrease quantity"
                      >
                        −
                      </button>
                      <span className="min-w-[2rem] text-center text-sm font-medium">
                        {item.quantity}
                      </span>
                      <button
                        type="button"
                        onClick={() => updateQuantity(item.productId, item.quantity + 1)}
                        className="px-3 py-1.5 text-soil-600 hover:bg-soil-50"
                        aria-label="Increase quantity"
                      >
                        +
                      </button>
                    </div>
                    <p className="min-w-[5rem] text-right font-semibold text-soil-900">
                      {formatMoney(Number(item.price) * item.quantity)}
                    </p>
                    <button
                      type="button"
                      onClick={() => removeFromCart(item.productId)}
                      className="text-sm text-red-600 hover:text-red-700"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              </article>
            ))}
          </div>

          <aside className="h-fit rounded-2xl border border-soil-200 bg-soil-50 p-6">
            <h2 className="font-display text-lg font-bold text-soil-900">
              Order summary
            </h2>

            <div className="mt-4 space-y-2 text-sm">
              <div className="flex justify-between text-soil-600">
                <span>Subtotal</span>
                <span>{formatMoney(subtotal)}</span>
              </div>
              <div className="flex justify-between border-t border-soil-200 pt-2 text-base font-bold text-soil-900">
                <span>Total</span>
                <span>{formatMoney(subtotal)}</span>
              </div>
            </div>

            {user ? (
              <p className="mt-4 text-sm text-soil-600">
                Account balance:{" "}
                <span className="font-semibold text-sprout-600">
                  {formatMoney(user.balance ?? 0)}
                </span>
              </p>
            ) : (
              <p className="mt-4 text-sm text-soil-500">
                <Link to="/login" state={{ from: "/cart" }} className="text-sprout-600 hover:underline">
                  Sign in
                </Link>{" "}
                to complete checkout.
              </p>
            )}

            <button
              type="button"
              onClick={handleCheckout}
              disabled={checkingOut || items.length === 0}
              className="mt-6 w-full rounded-full bg-sprout-500 py-3 text-sm font-semibold text-white hover:bg-sprout-600 disabled:opacity-60"
            >
              {checkingOut
                ? "Processing…"
                : user
                  ? "Place order"
                  : "Sign in to checkout"}
            </button>

            <p className="mt-3 text-center text-xs text-soil-500">
              Simulated checkout — balance is deducted on success.
            </p>
          </aside>
        </div>
      )}
    </div>
  );
}
