// Websites/Opus_NovaNest/src/components/solid/CartPage.tsx
import { createSignal, For, onMount, Show } from 'solid-js';
import { useStore } from '@nanostores/solid';
import {
  cartItems,
  cartTotalCents,
  clearCart,
  hydrateCart,
  removeFromCart,
  updateCartQuantity,
} from '../../stores/cart';
import { formatPrice } from '../../lib/format';

interface User {
  id: number;
  username: string;
  displayName: string;
  balanceCents: number;
}

interface Props {
  user: User | null;
}

export default function CartPage(props: Props) {
  if (typeof window !== 'undefined') {
    hydrateCart();
  }
  onMount(() => hydrateCart());

  const items = useStore(cartItems);
  const totalCents = useStore(cartTotalCents);
  const [balanceCents, setBalanceCents] = createSignal(props.user?.balanceCents ?? 0);
  const [message, setMessage] = createSignal<{ type: 'ok' | 'err'; text: string } | null>(
    null,
  );
  const [loading, setLoading] = createSignal(false);

  const canCheckout = () =>
    props.user != null && items().length > 0 && balanceCents() >= totalCents();

  async function handleCheckout() {
    if (!props.user) {
      window.location.href = `/login?redirect=${encodeURIComponent('/cart')}`;
      return;
    }

    if (items().length === 0) {
      setMessage({ type: 'err', text: 'Your cart is empty.' });
      return;
    }

    setLoading(true);
    setMessage(null);

    try {
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          items: items().map((i) => ({
            productId: i.productId,
            quantity: i.quantity,
          })),
        }),
      });
      const json = await res.json();

      if (!res.ok) {
        setMessage({
          type: 'err',
          text: json.error ?? 'Checkout failed. Please try again.',
        });
        setLoading(false);
        return;
      }

      if (json.order?.id) {
        clearCart();
        window.location.href = `/orders/${json.order.id}/confirmation`;
        return;
      }

      setBalanceCents(json.user.balanceCents);
      setMessage({
        type: 'err',
        text: 'Order placed but confirmation page is unavailable. Check Profile → Order history.',
      });
    } catch {
      setMessage({ type: 'err', text: 'Network error. Please try again.' });
    } finally {
      setLoading(false);
    }
  }

  const inputClass =
    'w-16 rounded-lg border border-white/10 bg-nest-900 px-2 py-1 text-center text-sm text-white focus:border-accent/50 focus:outline-none';

  return (
    <div class="space-y-8">
      <div>
        <h1 class="font-display text-3xl font-bold text-white">Shopping cart</h1>
        <p class="mt-2 text-nest-100/60">Review items and complete your simulated checkout.</p>
      </div>

      <Show when={message()}>
        <div
          class:list={[
            'rounded-lg border px-4 py-3 text-sm',
            message()!.type === 'ok'
              ? 'border-accent/30 bg-accent/10 text-accent'
              : 'border-red-500/30 bg-red-500/10 text-red-300',
          ]}
          role="alert"
        >
          {message()!.text}
        </div>
      </Show>

      <Show
        when={props.user}
        fallback={
          <p class="rounded-xl border border-white/10 bg-nest-900/50 px-4 py-3 text-sm text-nest-100/70">
            <a href="/login?redirect=%2Fcart" class="font-medium text-accent hover:underline">
              Sign in
            </a>{' '}
            to see your account balance and complete checkout.
          </p>
        }
      >
        <div class="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 bg-nest-900/50 px-5 py-4">
          <p class="text-sm text-nest-100/70">
            Signed in as <span class="text-white">{props.user!.displayName}</span>
          </p>
          <p class="font-display text-lg font-semibold text-accent">
            Balance: {formatPrice(balanceCents())}
          </p>
        </div>
      </Show>

      <Show
        when={items().length > 0}
        fallback={
          <div class="rounded-2xl border border-dashed border-white/20 p-12 text-center">
            <p class="text-nest-100/60">Your cart is empty.</p>
            <a
              href="/catalog"
              class="mt-4 inline-block text-sm font-medium text-accent hover:underline"
            >
              Browse products →
            </a>
            <p class="mt-4 text-sm text-nest-100/50">
              Past orders and invoices are in{' '}
              <a href="/profile" class="text-accent hover:underline">
                your profile
              </a>
              .
            </p>
          </div>
        }
      >
        <ul class="divide-y divide-white/10 overflow-hidden rounded-2xl border border-white/10">
          <For each={items()}>
            {(item) => (
              <li class="flex flex-col gap-4 bg-nest-900/40 p-5 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h2 class="font-display font-semibold text-white">{item.name}</h2>
                  <p class="text-sm text-nest-100/60">{formatPrice(item.priceCents)} each</p>
                </div>
                <div class="flex flex-wrap items-center gap-4">
                  <label class="flex items-center gap-2 text-sm text-nest-100/70">
                    Qty
                    <input
                      type="number"
                      min={1}
                      max={99}
                      class={inputClass}
                      value={item.quantity}
                      onInput={(e) =>
                        updateCartQuantity(
                          item.productId,
                          Math.max(1, Number.parseInt(e.currentTarget.value, 10) || 1),
                        )
                      }
                    />
                  </label>
                  <p class="min-w-[5rem] text-right font-medium text-white">
                    {formatPrice(item.priceCents * item.quantity)}
                  </p>
                  <button
                    type="button"
                    class="text-sm text-red-300 hover:underline"
                    onClick={() => removeFromCart(item.productId)}
                  >
                    Remove
                  </button>
                </div>
              </li>
            )}
          </For>
        </ul>

        <div class="rounded-2xl border border-white/10 bg-nest-900/50 p-6">
          <div class="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p class="text-sm text-nest-100/60">Order total</p>
              <p class="font-display text-2xl font-bold text-white">
                {formatPrice(totalCents())}
              </p>
              <Show when={props.user && balanceCents() < totalCents()}>
                <p class="mt-2 text-sm text-red-300">
                  Insufficient balance — you need{' '}
                  {formatPrice(totalCents() - balanceCents())} more.
                </p>
              </Show>
            </div>
            <button
              type="button"
              disabled={loading() || !canCheckout()}
              onClick={handleCheckout}
              class="rounded-full bg-accent px-6 py-3 text-sm font-semibold text-nest-950 transition hover:bg-accent/90 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {loading() ? 'Processing…' : 'Complete checkout'}
            </button>
          </div>
          <Show when={!props.user}>
            <p class="mt-4 text-sm text-nest-100/60">
              You must be signed in to check out.
            </p>
          </Show>
        </div>
      </Show>

      <p class="text-sm text-nest-100/50">
        <a href="/" class="text-accent hover:underline">
          ← Continue shopping
        </a>
      </p>
    </div>
  );
}

// Génération_Code_Application/Opus_PureRoots/frontend/src/pages/CartPage.tsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { downloadInvoice, formatMoney, submitCheckout } from "../api/checkout";
import { useAuth } from "../context/AuthContext";
import { useCart } from "../context/CartContext";

export default function CartPage() {
  const { items, itemCount, subtotal, updateQuantity, removeItem, clearCart } = useCart();
  const { user, refreshUser } = useAuth();
  const navigate = useNavigate();

  const [checkingOut, setCheckingOut] = useState(false);
  const [downloadingInvoice, setDownloadingInvoice] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [lastOrderId, setLastOrderId] = useState<number | null>(null);

  const balance = user ? Number(user.balance) : 0;
  const canAfford = user ? balance >= subtotal : false;

  async function handleDownloadInvoice() {
    if (!lastOrderId) return;
    setDownloadingInvoice(true);
    setError(null);
    try {
      await downloadInvoice(lastOrderId);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Invoice download failed");
    } finally {
      setDownloadingInvoice(false);
    }
  }

  async function handleCheckout() {
    if (!user) {
      navigate("/login", { state: { from: "/cart" } });
      return;
    }
    if (items.length === 0) return;

    setCheckingOut(true);
    setError(null);
    setSuccess(null);
    setLastOrderId(null);

    try {
      const result = await submitCheckout(
        items.map((i) => ({ product_id: i.product.id, quantity: i.quantity }))
      );
      clearCart();
      await refreshUser();
      setLastOrderId(result.order_id);
      setSuccess(
        `${result.message} Order #${result.order_id} — ${formatMoney(result.total)} charged. New balance: ${formatMoney(result.new_balance)}.`
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "Checkout failed");
    } finally {
      setCheckingOut(false);
    }
  }

  if (items.length === 0 && !success) {
    return (
      <div className="mx-auto max-w-2xl px-6 py-20 text-center">
        <h1 className="font-display text-3xl font-semibold text-forest-800">Your cart</h1>
        <p className="mt-4 text-stone-600">Your cart is empty.</p>
        <Link
          to="/#products"
          className="mt-8 inline-block rounded-full bg-forest-600 px-8 py-3 text-sm font-semibold text-white hover:bg-forest-700"
        >
          Continue shopping
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-6 py-12">
      <h1 className="font-display text-3xl font-semibold text-forest-800">Your cart</h1>
      <p className="mt-2 text-stone-600">
        {itemCount} {itemCount === 1 ? "item" : "items"} — checkout uses your account balance.
      </p>

      {success && (
        <div className="mt-6 rounded-xl border border-green-200 bg-green-50 px-4 py-4 text-sm text-green-900">
          <p className="font-medium">Order complete</p>
          <p className="mt-1">{success}</p>
          <div className="mt-4 flex flex-wrap gap-3">
            {lastOrderId && (
              <button
                type="button"
                onClick={handleDownloadInvoice}
                disabled={downloadingInvoice}
                className="rounded-full bg-forest-600 px-5 py-2 text-sm font-semibold text-white hover:bg-forest-700 disabled:opacity-50"
              >
                {downloadingInvoice ? "Preparing PDF…" : "Download invoice (PDF)"}
              </button>
            )}
            <Link
              to="/"
              className="inline-flex items-center rounded-full border border-forest-300 px-5 py-2 text-sm font-medium text-forest-700 hover:bg-forest-50"
            >
              Continue shopping →
            </Link>
          </div>
        </div>
      )}

      {error && (
        <div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-4 text-sm text-red-900">
          <p className="font-medium">Checkout could not be completed</p>
          <p className="mt-1">{error}</p>
          {user && !canAfford && subtotal > 0 && (
            <p className="mt-2">
              Your balance is {formatMoney(balance)} but the order total is {formatMoney(subtotal)}.
              Ask an admin to add funds, or remove items from your cart.
            </p>
          )}
        </div>
      )}

      {items.length > 0 && (
        <div className="mt-8 grid gap-8 lg:grid-cols-3">
          <ul className="space-y-4 lg:col-span-2">
            {items.map(({ product, quantity }) => (
              <li
                key={product.id}
                className="flex gap-4 rounded-2xl border border-forest-200/80 bg-white p-4 shadow-sm"
              >
                <div className="h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-forest-50">
                  {product.image_url ? (
                    <img src={product.image_url} alt="" className="h-full w-full object-cover" />
                  ) : (
                    <div className="flex h-full items-center justify-center text-2xl">🌿</div>
                  )}
                </div>
                <div className="flex flex-1 flex-col">
                  <h2 className="font-semibold text-forest-800">{product.name}</h2>
                  <p className="mt-1 text-sm text-stone-600">{formatMoney(product.price)} each</p>
                  <div className="mt-auto flex flex-wrap items-center gap-3 pt-3">
                    <label className="flex items-center gap-2 text-sm text-stone-600">
                      Qty
                      <input
                        type="number"
                        min={1}
                        max={99}
                        value={quantity}
                        onChange={(e) =>
                          updateQuantity(product.id, parseInt(e.target.value, 10) || 1)
                        }
                        className="w-16 rounded-lg border border-forest-200 px-2 py-1"
                      />
                    </label>
                    <button
                      type="button"
                      onClick={() => removeItem(product.id)}
                      className="text-sm text-red-600 hover:text-red-800"
                    >
                      Remove
                    </button>
                    <span className="ml-auto font-semibold text-forest-700">
                      {formatMoney(Number(product.price) * quantity)}
                    </span>
                  </div>
                </div>
              </li>
            ))}
          </ul>

          <aside className="h-fit rounded-2xl border border-forest-200/80 bg-white p-6 shadow-sm">
            <h2 className="text-lg font-semibold text-forest-800">Order summary</h2>
            <dl className="mt-4 space-y-2 text-sm">
              <div className="flex justify-between">
                <dt className="text-stone-600">Subtotal</dt>
                <dd className="font-medium">{formatMoney(subtotal)}</dd>
              </div>
              {user && (
                <div className="flex justify-between border-t border-forest-100 pt-2">
                  <dt className="text-stone-600">Account balance</dt>
                  <dd className={canAfford ? "font-medium text-forest-700" : "font-medium text-red-600"}>
                    {formatMoney(balance)}
                  </dd>
                </div>
              )}
            </dl>

            {!user && (
              <p className="mt-4 rounded-lg bg-forest-50 px-3 py-2 text-sm text-forest-800">
                <Link to="/login" state={{ from: "/cart" }} className="font-medium underline">
                  Sign in
                </Link>{" "}
                to complete checkout with your account balance.
              </p>
            )}

            {user && !canAfford && subtotal > 0 && (
              <p className="mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800">
                Insufficient balance. You need {formatMoney(subtotal - balance)} more.
              </p>
            )}

            <button
              type="button"
              onClick={handleCheckout}
              disabled={checkingOut || !user || items.length === 0 || (user && !canAfford)}
              className="mt-6 w-full rounded-full bg-forest-600 py-3 text-sm font-semibold text-white transition hover:bg-forest-700 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {checkingOut ? "Processing…" : "Complete checkout (simulation)"}
            </button>
            <p className="mt-3 text-center text-xs text-stone-500">
              Simulated payment — balance is deducted instantly.
            </p>
          </aside>
        </div>
      )}
    </div>
  );
}
