// Websites/GPT5.5_GamerGrid/src/components/solid/ProductCsvImport.tsx
import { createSignal, Show } from 'solid-js';
import type { ProductDTO } from '@/lib/types';

interface Props {
  categories: { id: string; name: string; slug: string }[];
  onImported: (products: ProductDTO[]) => void;
  onFlash: (message: string, isError?: boolean) => void;
}

type ImportResult = {
  created: number;
  failed: number;
  errors: { row: number; message: string }[];
};

export default function ProductCsvImport(props: Props) {
  const [file, setFile] = createSignal<File | null>(null);
  const [loading, setLoading] = createSignal(false);
  const [result, setResult] = createSignal<ImportResult | null>(null);

  const handleImport = async () => {
    const selected = file();
    if (!selected) {
      props.onFlash('Choose a CSV file first.', true);
      return;
    }

    setLoading(true);
    setResult(null);

    const formData = new FormData();
    formData.append('file', selected);

    try {
      const res = await fetch('/api/admin/products/import', {
        method: 'POST',
        body: formData,
      });
      const json = await res.json();

      if (!res.ok && !json.created) {
        throw new Error(json.error ?? 'Import failed.');
      }

      setResult({
        created: json.created ?? 0,
        failed: json.failed ?? 0,
        errors: json.errors ?? [],
      });

      if (json.products?.length) {
        props.onImported(json.products);
      }

      if (json.created > 0) {
        props.onFlash(
          `Imported ${json.created} product${json.created === 1 ? '' : 's'}${
            json.failed ? ` (${json.failed} row${json.failed === 1 ? '' : 's'} skipped)` : ''
          }.`,
        );
      } else {
        props.onFlash('No products were created. Check row errors below.', true);
      }

      setFile(null);
    } catch (err) {
      props.onFlash(err instanceof Error ? err.message : 'Import failed.', true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="rounded-2xl border border-stream-500/20 bg-slate-900/60 p-6 space-y-4">
      <div>
        <h3 class="text-lg font-semibold text-white">Import products from CSV</h3>
        <p class="mt-2 text-sm text-slate-400">
          Upload a comma-separated file to create multiple products at once. Download the{' '}
          <a
            href="/samples/products-import-sample.csv"
            class="font-medium text-volt-400 hover:text-volt-300 underline-offset-2 hover:underline"
            download
          >
            sample CSV
          </a>{' '}
          to see the required format.
        </p>
      </div>

      <dl class="grid gap-2 text-xs text-slate-500 sm:grid-cols-2">
        <div>
          <dt class="font-medium text-slate-400">Required columns</dt>
          <dd class="mt-1 font-mono">
            category_id <span class="text-slate-600">or</span> category_slug, name, description,
            price, image
          </dd>
        </div>
        <div>
          <dt class="font-medium text-slate-400">Optional columns</dt>
          <dd class="mt-1 font-mono">slug, badge, featured (true/false)</dd>
        </div>
      </dl>

      <Show when={props.categories.length > 0}>
        <p class="text-xs text-slate-500">
          Valid category IDs:{' '}
          {props.categories.map((c) => (
            <code class="mr-2 rounded bg-black/30 px-1 py-0.5 text-stream-400">{c.id}</code>
          ))}
        </p>
      </Show>

      <div class="flex flex-col gap-3 sm:flex-row sm:items-end">
        <label class="flex-1 text-sm">
          <span class="text-slate-400">CSV file</span>
          <input
            type="file"
            accept=".csv,text/csv"
            class="mt-1 block w-full text-sm text-slate-300 file:mr-4 file:rounded-full file:border-0 file:bg-volt-600 file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-volt-500"
            onChange={(e) => setFile(e.currentTarget.files?.[0] ?? null)}
          />
        </label>
        <button
          type="button"
          disabled={loading() || !file()}
          onClick={handleImport}
          class="rounded-full bg-stream-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-stream-500 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {loading() ? 'Importing…' : 'Upload & import'}
        </button>
      </div>

      <Show when={result()}>
        {(r) => (
          <div class="rounded-lg border border-white/10 bg-slate-950/50 p-4 text-sm">
            <p class="text-slate-300">
              <span class="font-medium text-stream-400">{r().created}</span> created ·{' '}
              <span class="font-medium text-amber-400">{r().failed}</span> failed
            </p>
            <Show when={r().errors.length > 0}>
              <ul class="mt-3 max-h-40 space-y-1 overflow-y-auto text-xs text-red-200/90">
                {r().errors.map((err) => (
                  <li>
                    Row {err.row}: {err.message}
                  </li>
                ))}
              </ul>
            </Show>
          </div>
        )}
      </Show>
    </div>
  );
}

// Websites/Codex5.3_HydroFlasked/src/components/admin/ProductCsvImport.tsx
"use client";

import { useRef, useState } from "react";
import type { Product } from "../../../generated/prisma/client";
import { parseApiResponse } from "@/lib/parse-api-response";

type ImportError = { row: number; message: string };

type ProductCsvImportProps = {
  onImported: (products: Product[]) => void;
};

export function ProductCsvImport({ onImported }: ProductCsvImportProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [importErrors, setImportErrors] = useState<ImportError[]>([]);

  async function handleUpload(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const file = fileInputRef.current?.files?.[0];
    if (!file) {
      setError("Choose a CSV file to upload");
      return;
    }

    setLoading(true);
    setError(null);
    setMessage(null);
    setImportErrors([]);

    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch("/api/admin/products/import", {
        method: "POST",
        body: formData,
      });

      const data = await parseApiResponse(res);

      if (!res.ok) {
        setError((data.error as string) ?? "Import failed");
        return;
      }

      const created = (data.created as number) ?? 0;
      const failed = (data.failed as number) ?? 0;
      const products = (data.products as Product[]) ?? [];
      const errors = (data.errors as ImportError[]) ?? [];

      if (products.length > 0) {
        onImported(products);
      }

      setImportErrors(errors);

      if (created > 0 && failed === 0) {
        setMessage(`Successfully imported ${created} product${created !== 1 ? "s" : ""}.`);
      } else if (created > 0) {
        setMessage(
          `Imported ${created} product${created !== 1 ? "s" : ""}; ${failed} row${failed !== 1 ? "s" : ""} failed.`,
        );
      } else {
        setError("No products were imported. Fix the errors below and try again.");
      }

      if (fileInputRef.current) fileInputRef.current.value = "";
    } catch {
      setError("Network error during import.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="rounded-2xl border border-white/10 bg-slate-900/50 p-6">
      <h3 className="text-lg font-semibold text-white">Import products from CSV</h3>
      <p className="mt-2 text-sm text-slate-400">
        Upload a comma-separated file to bulk-create catalog items. Duplicate slugs in the
        file or database are skipped with an error.
      </p>

      <div className="mt-4 rounded-xl border border-dashed border-white/15 bg-slate-950/50 p-4 text-sm text-slate-400">
        <p className="font-medium text-slate-300">Required columns</p>
        <p className="mt-1 font-mono text-xs">
          name, slug, description, category, price_dollars
        </p>
        <p className="mt-3 font-medium text-slate-300">Optional columns</p>
        <p className="mt-1 font-mono text-xs">
          price_cents, image_url, featured, in_stock
        </p>
        <p className="mt-3">
          <span className="text-slate-300">Category values: </span>
          TUMBLER, GLASSWARE, WINE_MUG
        </p>
        <a
          href="/samples/products-import-sample.csv"
          download="products-import-sample.csv"
          className="mt-4 inline-flex text-sm font-medium text-brand-400 hover:text-brand-300"
        >
          Download sample CSV →
        </a>
      </div>

      <form onSubmit={handleUpload} className="mt-6 flex flex-wrap items-end gap-4">
        <label className="min-w-[200px] flex-1">
          <span className="text-sm text-slate-300">CSV file</span>
          <input
            ref={fileInputRef}
            type="file"
            accept=".csv,text/csv"
            required
            className="mt-2 block w-full text-sm text-slate-400 file:mr-4 file:rounded-full file:border-0 file:bg-brand-500 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-brand-400"
          />
        </label>
        <button
          type="submit"
          disabled={loading}
          className="rounded-full bg-brand-500 px-6 py-2.5 text-sm font-semibold text-white hover:bg-brand-400 disabled:opacity-50"
        >
          {loading ? "Importing…" : "Upload & import"}
        </button>
      </form>

      {message ? (
        <p className="mt-4 rounded-lg bg-brand-500/10 px-3 py-2 text-sm text-brand-200">
          {message}
        </p>
      ) : null}
      {error ? (
        <p className="mt-4 rounded-lg bg-red-500/10 px-3 py-2 text-sm text-red-300">
          {error}
        </p>
      ) : null}

      {importErrors.length > 0 ? (
        <div className="mt-4">
          <p className="text-sm font-medium text-amber-300">Import issues</p>
          <ul className="mt-2 max-h-40 space-y-1 overflow-y-auto text-sm text-slate-400">
            {importErrors.map((err, idx) => (
              <li key={`${err.row}-${idx}`}>
                {err.row > 0 ? (
                  <>
                    Row {err.row}: {err.message}
                  </>
                ) : (
                  err.message
                )}
              </li>
            ))}
          </ul>
        </div>
      ) : null}
    </section>
  );
}
