// Génération_Code_Application/Composer2.5_SproutSoil/frontend/src/pages/CartPage.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { checkoutApi, formatMoney, invoiceApi } from "../api/client";
import { useAuth } from "../context/AuthContext";
import { useCart } from "../context/CartContext";

export default function CartPage() {
  const { items, subtotal, itemCount, updateQuantity, removeFromCart, clearCart } =
    useCart();
  const { user, updateUser } = useAuth();
  const navigate = useNavigate();

  const [checkingOut, setCheckingOut] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [invoiceNumber, setInvoiceNumber] = useState(null);
  const [downloading, setDownloading] = useState(false);

  const handleCheckout = async () => {
    if (!user) {
      navigate("/login", { state: { from: "/cart" } });
      return;
    }

    if (items.length === 0) return;

    setCheckingOut(true);
    setError("");
    setSuccess("");

    try {
      const result = await checkoutApi.placeOrder({
        items: items.map((i) => ({
          product_id: i.productId,
          quantity: i.quantity,
        })),
      });
      updateUser(result.user);
      clearCart();
      setInvoiceNumber(result.invoice_number);
      setSuccess(
        `${result.message} Total charged: ${formatMoney(result.total)}. ` +
          `New balance: ${formatMoney(result.new_balance)}. ` +
          `Invoice: ${result.invoice_number}.`
      );
    } catch (err) {
      setError(err.message);
    } finally {
      setCheckingOut(false);
    }
  };

  if (items.length === 0 && !success) {
    return (
      <div className="mx-auto max-w-2xl px-6 py-20 text-center">
        <p className="text-5xl">🛒</p>
        <h1 className="mt-4 font-display text-3xl font-bold text-soil-950">
          Your cart is empty
        </h1>
        <p className="mt-2 text-soil-600">
          Browse our indoor gardening essentials and add something you love.
        </p>
        <Link
          to="/#products"
          className="mt-8 inline-block rounded-full bg-sprout-500 px-8 py-3 text-sm font-semibold text-white hover:bg-sprout-600"
        >
          Shop products
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-6 py-12">
      <h1 className="font-display text-3xl font-bold text-soil-950">
        Shopping cart
      </h1>
      <p className="mt-2 text-soil-600">
        {itemCount} {itemCount === 1 ? "item" : "items"} in your cart
      </p>

      {success && (
        <div className="mt-6 rounded-2xl bg-sprout-500/10 px-5 py-4 ring-1 ring-sprout-500/20">
          <p className="font-medium text-sprout-800">Order complete</p>
          <p className="mt-1 text-sm text-sprout-700">{success}</p>
          <div className="mt-4 flex flex-wrap gap-3">
            {invoiceNumber && (
              <button
                type="button"
                disabled={downloading}
                onClick={async () => {
                  setDownloading(true);
                  try {
                    await invoiceApi.downloadPdf(invoiceNumber);
                  } catch (err) {
                    setError(err.message);
                  } finally {
                    setDownloading(false);
                  }
                }}
                className="rounded-full bg-soil-800 px-5 py-2 text-sm font-medium text-white hover:bg-soil-700 disabled:opacity-60"
              >
                {downloading ? "Downloading…" : "Download invoice (PDF)"}
              </button>
            )}
            <Link
              to="/catalog"
              className="inline-flex items-center rounded-full border border-soil-200 px-5 py-2 text-sm font-medium text-soil-700 hover:bg-soil-100"
            >
              Continue shopping
            </Link>
          </div>
        </div>
      )}

      {error && (
        <p className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700 ring-1 ring-red-200">
          {error}
        </p>
      )}

      {items.length > 0 && (
        <div className="mt-8 grid gap-8 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-4">
            {items.map((item) => (
              <article
                key={item.productId}
                className="flex gap-4 rounded-2xl border border-soil-200 bg-white p-4"
              >
                <div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-soil-100">
                  {item.image_url ? (
                    <img
                      src={item.image_url}
                      alt=""
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <span className="flex h-full w-full items-center justify-center text-2xl">
                      🌿
                    </span>
                  )}
                </div>

                <div className="flex flex-1 flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                  <div>
                    <h2 className="font-medium text-soil-900">{item.name}</h2>
                    <p className="text-sm text-soil-500">
                      {formatMoney(item.price)} each
                    </p>
                  </div>

                  <div className="flex items-center gap-3">
                    <div className="flex items-center rounded-lg border border-soil-200">
                      <button
                        type="button"
                        onClick={() => updateQuantity(item.productId, item.quantity - 1)}
                        className="px-3 py-1.5 text-soil-600 hover:bg-soil-50"
                        aria-label="Decrease quantity"
                      >
                        −
                      </button>
                      <span className="min-w-[2rem] text-center text-sm font-medium">
                        {item.quantity}
                      </span>
                      <button
                        type="button"
                        onClick={() => updateQuantity(item.productId, item.quantity + 1)}
                        className="px-3 py-1.5 text-soil-600 hover:bg-soil-50"
                        aria-label="Increase quantity"
                      >
                        +
                      </button>
                    </div>
                    <p className="min-w-[5rem] text-right font-semibold text-soil-900">
                      {formatMoney(Number(item.price) * item.quantity)}
                    </p>
                    <button
                      type="button"
                      onClick={() => removeFromCart(item.productId)}
                      className="text-sm text-red-600 hover:text-red-700"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              </article>
            ))}
          </div>

          <aside className="h-fit rounded-2xl border border-soil-200 bg-soil-50 p-6">
            <h2 className="font-display text-lg font-bold text-soil-900">
              Order summary
            </h2>

            <div className="mt-4 space-y-2 text-sm">
              <div className="flex justify-between text-soil-600">
                <span>Subtotal</span>
                <span>{formatMoney(subtotal)}</span>
              </div>
              <div className="flex justify-between border-t border-soil-200 pt-2 text-base font-bold text-soil-900">
                <span>Total</span>
                <span>{formatMoney(subtotal)}</span>
              </div>
            </div>

            {user ? (
              <p className="mt-4 text-sm text-soil-600">
                Account balance:{" "}
                <span className="font-semibold text-sprout-600">
                  {formatMoney(user.balance ?? 0)}
                </span>
              </p>
            ) : (
              <p className="mt-4 text-sm text-soil-500">
                <Link to="/login" state={{ from: "/cart" }} className="text-sprout-600 hover:underline">
                  Sign in
                </Link>{" "}
                to complete checkout.
              </p>
            )}

            <button
              type="button"
              onClick={handleCheckout}
              disabled={checkingOut || items.length === 0}
              className="mt-6 w-full rounded-full bg-sprout-500 py-3 text-sm font-semibold text-white hover:bg-sprout-600 disabled:opacity-60"
            >
              {checkingOut
                ? "Processing…"
                : user
                  ? "Place order"
                  : "Sign in to checkout"}
            </button>

            <p className="mt-3 text-center text-xs text-soil-500">
              Simulated checkout — balance is deducted on success.
            </p>
          </aside>
        </div>
      )}
    </div>
  );
}

// Génération_Code_Application/Composer2.5_LunaLuxe/src/components/solid/CartPage.tsx
import { Show, For, onMount } from 'solid-js';
import { useStore } from '@nanostores/solid';
import { $cart, $cartTotal } from '@/stores/cart-actions';
import { hydrateCartFromStorage, removeFromCart, updateCartQuantity } from '@/stores/cart-actions';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' }).format(price);

export default function CartPage() {
  const cart = useStore($cart);
  const total = useStore($cartTotal);

  onMount(() => {
    hydrateCartFromStorage();
  });

  return (
    <div>
      <Show
        when={cart().items.length > 0}
        fallback={
          <div class="rounded-2xl border border-luna-200 bg-white px-6 py-16 text-center shadow-sm">
            <p class="font-serif text-xl text-luna-800">Your cart is empty</p>
            <p class="mt-2 text-sm text-luna-500">Add sleep essentials from our shop to get started.</p>
            <a
              href="/#products"
              class="mt-6 inline-block rounded-full bg-luna-800 px-8 py-3 text-sm font-semibold text-luna-50 hover:bg-luna-700"
            >
              Browse products
            </a>
          </div>
        }
      >
        <div class="space-y-4">
          <For each={cart().items}>
            {(item) => (
              <article class="flex flex-col gap-4 rounded-2xl border border-luna-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center">
                <img
                  src={item.imageUrl}
                  alt={item.name}
                  class="h-24 w-24 shrink-0 rounded-xl object-cover"
                />
                <div class="min-w-0 flex-1">
                  <h2 class="font-medium text-luna-900">{item.name}</h2>
                  <p class="text-sm text-luna-500">{formatPrice(item.price)} each</p>
                </div>
                <div class="flex items-center gap-3">
                  <label class="sr-only" for={`qty-${item.productId}`}>
                    Quantity for {item.name}
                  </label>
                  <button
                    type="button"
                    onClick={() => updateCartQuantity(item.productId, item.quantity - 1)}
                    class="flex h-9 w-9 items-center justify-center rounded-full border border-luna-300 text-luna-700 hover:bg-luna-100"
                    aria-label="Decrease quantity"
                  >
                    −
                  </button>
                  <input
                    id={`qty-${item.productId}`}
                    type="number"
                    min="1"
                    max="99"
                    value={item.quantity}
                    onChange={(e) =>
                      updateCartQuantity(item.productId, parseInt(e.currentTarget.value, 10) || 1)
                    }
                    class="w-14 rounded-lg border border-luna-200 bg-luna-50 px-2 py-1.5 text-center text-sm"
                  />
                  <button
                    type="button"
                    onClick={() => updateCartQuantity(item.productId, item.quantity + 1)}
                    class="flex h-9 w-9 items-center justify-center rounded-full border border-luna-300 text-luna-700 hover:bg-luna-100"
                    aria-label="Increase quantity"
                  >
                    +
                  </button>
                </div>
                <div class="text-right">
                  <p class="text-sm font-semibold text-luna-900">
                    {formatPrice(item.price * item.quantity)}
                  </p>
                  <button
                    type="button"
                    onClick={() => removeFromCart(item.productId)}
                    class="mt-1 text-xs text-luna-400 hover:text-luna-700"
                  >
                    Remove
                  </button>
                </div>
              </article>
            )}
          </For>
        </div>

        <aside class="mt-8 rounded-2xl border border-luna-200 bg-white p-6 shadow-sm">
          <div class="flex items-center justify-between border-b border-luna-100 pb-4">
            <span class="text-sm text-luna-600">Order subtotal</span>
            <span class="text-2xl font-semibold text-luna-900">{formatPrice(total())}</span>
          </div>
          <a
            href="/checkout"
            class="mt-4 block w-full rounded-full bg-lavender-500 py-3 text-center text-sm font-semibold text-white hover:bg-lavender-400"
          >
            Proceed to checkout
          </a>
          <a
            href="/#products"
            class="mt-3 block w-full py-2 text-center text-sm text-luna-500 hover:text-luna-800"
          >
            Continue shopping
          </a>
        </aside>
      </Show>
    </div>
  );
}
