// Génération_Code_Application/Sonnet_4.6_Solace_Ground/src/components/solid/ProfileForm.tsx
import { createSignal, Show } from 'solid-js';
import type { PublicUser } from '@/types/auth';
import { formatPrice } from '@/lib/utils';

type Props = {
  initialUser: PublicUser;
};

const inputClass =
  'mt-1 w-full rounded-lg border border-cork-300 bg-white px-4 py-2.5 text-cork-900 placeholder:text-cork-400 focus:border-cork-600 focus:outline-none focus:ring-1 focus:ring-cork-600';

export default function ProfileForm(props: Props) {
  const [user, setUser] = createSignal(props.initialUser);
  const [username, setUsername] = createSignal(props.initialUser.username);
  const [email, setEmail] = createSignal(props.initialUser.email);
  const [displayName, setDisplayName] = createSignal(props.initialUser.displayName ?? '');
  const [bio, setBio] = createSignal(props.initialUser.bio ?? '');
  const [avatarUrl, setAvatarUrl] = createSignal(props.initialUser.avatarUrl ?? '');
  const [currentPassword, setCurrentPassword] = createSignal('');
  const [newPassword, setNewPassword] = createSignal('');
  const [errors, setErrors] = createSignal<Record<string, string>>({});
  const [message, setMessage] = createSignal('');
  const [error, setError] = createSignal('');
  const [saving, setSaving] = createSignal(false);
  const [uploading, setUploading] = createSignal(false);
  const [deleting, setDeleting] = createSignal(false);

  async function handleSave(e: Event) {
    e.preventDefault();
    setErrors({});
    setMessage('');
    setError('');
    setSaving(true);

    try {
      const res = await fetch('/api/profile', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'same-origin',
        body: JSON.stringify({
          username: username(),
          email: email(),
          displayName: displayName(),
          bio: bio(),
          avatarUrl: avatarUrl(),
          currentPassword: currentPassword() || undefined,
          newPassword: newPassword() || undefined,
        }),
      });
      const data = await res.json();

      if (!res.ok) {
        if (data.errors) setErrors(data.errors);
        else setError(data.error ?? 'Update failed.');
        return;
      }

      setUser(data.user);
      setCurrentPassword('');
      setNewPassword('');
      setMessage('Profile updated successfully.');
    } catch {
      setError('Network error. Please try again.');
    } finally {
      setSaving(false);
    }
  }

  async function handleAvatarUpload(e: Event) {
    const input = e.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    setUploading(true);
    setError('');
    setMessage('');

    const formData = new FormData();
    formData.append('avatar', file);

    try {
      const res = await fetch('/api/profile/avatar', {
        method: 'POST',
        credentials: 'same-origin',
        body: formData,
      });
      const data = await res.json();

      if (!res.ok) {
        setError(data.error ?? 'Upload failed.');
        return;
      }

      setUser(data.user);
      setAvatarUrl(data.user.avatarUrl ?? '');
      setMessage('Profile picture updated.');
    } catch {
      setError('Upload failed. Please try again.');
    } finally {
      setUploading(false);
      input.value = '';
    }
  }

  async function handleDelete() {
    if (
      !confirm(
        'Delete your account permanently? This cannot be undone.',
      )
    ) {
      return;
    }

    setDeleting(true);
    try {
      const res = await fetch('/api/profile', {
        method: 'DELETE',
        credentials: 'same-origin',
      });
      if (res.ok) {
        window.location.href = '/';
      } else {
        const data = await res.json();
        setError(data.error ?? 'Could not delete account.');
      }
    } catch {
      setError('Network error.');
    } finally {
      setDeleting(false);
    }
  }

  async function handleLogout() {
    await fetch('/api/auth/logout', { method: 'POST', credentials: 'same-origin' });
    window.location.href = '/';
  }

  const avatarSrc = () => user().avatarUrl || null;

  return (
    <div class="space-y-10">
      <p class="rounded-xl border border-cork-200 bg-cork-100/50 px-4 py-3 text-sm text-cork-700">
        Account balance: <span class="font-semibold text-cork-900">{formatPrice(user().balanceCents)}</span>
      </p>

      <section class="flex flex-col items-start gap-6 sm:flex-row sm:items-center">
        <div class="relative h-24 w-24 shrink-0 overflow-hidden rounded-full border-2 border-cork-300 bg-cork-100">
          <Show
            when={avatarSrc()}
            fallback={
              <span class="flex h-full w-full items-center justify-center font-serif text-2xl text-cork-500">
                {user().username.slice(0, 1).toUpperCase()}
              </span>
            }
          >
            <img
              src={avatarSrc()!}
              alt=""
              class="h-full w-full object-cover"
            />
          </Show>
        </div>
        <div class="flex-1 space-y-3">
          <p class="text-sm text-cork-600">
            Upload an image (max 2 MB) or set a picture URL below.
          </p>
          <label class="inline-flex cursor-pointer items-center rounded-full border border-cork-400 px-4 py-2 text-sm font-medium text-cork-800 hover:bg-cork-100">
            {uploading() ? 'Uploading…' : 'Upload image file'}
            <input
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif"
              class="sr-only"
              disabled={uploading()}
              onChange={handleAvatarUpload}
            />
          </label>
        </div>
      </section>

      <Show when={message()}>
        <p class="rounded-lg border border-sage-500/30 bg-sage-400/10 px-4 py-3 text-sm text-cork-800">
          {message()}
        </p>
      </Show>
      <Show when={error()}>
        <p class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">
          {error()}
        </p>
      </Show>

      <form onSubmit={handleSave} class="space-y-5">
        <div>
          <label for="avatarUrl" class="text-sm font-medium text-cork-800">
            Profile picture URL
          </label>
          <input
            id="avatarUrl"
            type="url"
            placeholder="https://example.com/photo.jpg"
            class={inputClass}
            value={avatarUrl()}
            onInput={(e) => setAvatarUrl(e.currentTarget.value)}
          />
          <Show when={errors().avatarUrl}>
            <p class="mt-1 text-sm text-red-700">{errors().avatarUrl}</p>
          </Show>
        </div>

        <div>
          <label for="username" class="text-sm font-medium text-cork-800">
            Username
          </label>
          <input
            id="username"
            required
            class={inputClass}
            value={username()}
            onInput={(e) => setUsername(e.currentTarget.value)}
          />
          <Show when={errors().username}>
            <p class="mt-1 text-sm text-red-700">{errors().username}</p>
          </Show>
        </div>

        <div>
          <label for="email" class="text-sm font-medium text-cork-800">
            Email
          </label>
          <input
            id="email"
            type="email"
            required
            class={inputClass}
            value={email()}
            onInput={(e) => setEmail(e.currentTarget.value)}
          />
          <Show when={errors().email}>
            <p class="mt-1 text-sm text-red-700">{errors().email}</p>
          </Show>
        </div>

        <div>
          <label for="displayName" class="text-sm font-medium text-cork-800">
            Display name
          </label>
          <input
            id="displayName"
            class={inputClass}
            value={displayName()}
            onInput={(e) => setDisplayName(e.currentTarget.value)}
          />
        </div>

        <div>
          <label for="bio" class="text-sm font-medium text-cork-800">
            Bio
          </label>
          <textarea
            id="bio"
            rows={4}
            class={inputClass}
            value={bio()}
            onInput={(e) => setBio(e.currentTarget.value)}
          />
          <Show when={errors().bio}>
            <p class="mt-1 text-sm text-red-700">{errors().bio}</p>
          </Show>
        </div>

        <fieldset class="rounded-xl border border-cork-200 p-5 space-y-4">
          <legend class="px-1 text-sm font-medium text-cork-800">
            Change password (optional)
          </legend>
          <div>
            <label for="currentPassword" class="text-sm text-cork-700">
              Current password
            </label>
            <input
              id="currentPassword"
              type="password"
              autocomplete="current-password"
              class={inputClass}
              value={currentPassword()}
              onInput={(e) => setCurrentPassword(e.currentTarget.value)}
            />
            <Show when={errors().currentPassword}>
              <p class="mt-1 text-sm text-red-700">{errors().currentPassword}</p>
            </Show>
          </div>
          <div>
            <label for="newPassword" class="text-sm text-cork-700">
              New password
            </label>
            <input
              id="newPassword"
              type="password"
              autocomplete="new-password"
              class={inputClass}
              value={newPassword()}
              onInput={(e) => setNewPassword(e.currentTarget.value)}
            />
            <Show when={errors().newPassword}>
              <p class="mt-1 text-sm text-red-700">{errors().newPassword}</p>
            </Show>
          </div>
        </fieldset>

        <div class="flex flex-wrap gap-3">
          <button
            type="submit"
            disabled={saving()}
            class="rounded-full bg-cork-800 px-6 py-2.5 text-sm font-medium text-cork-50 hover:bg-cork-700 disabled:opacity-60"
          >
            {saving() ? 'Saving…' : 'Save changes'}
          </button>
          <button
            type="button"
            onClick={handleLogout}
            class="rounded-full border border-cork-400 px-6 py-2.5 text-sm font-medium text-cork-800 hover:bg-cork-100"
          >
            Log out
          </button>
        </div>
      </form>

      <section class="border-t border-cork-200 pt-8">
        <h2 class="font-serif text-lg text-cork-900">Danger zone</h2>
        <p class="mt-2 text-sm text-cork-600">
          Permanently delete your account and all active sessions.
        </p>
        <button
          type="button"
          disabled={deleting()}
          onClick={handleDelete}
          class="mt-4 rounded-full border border-red-300 bg-red-50 px-6 py-2.5 text-sm font-medium text-red-800 hover:bg-red-100 disabled:opacity-60"
        >
          {deleting() ? 'Deleting…' : 'Delete my account'}
        </button>
      </section>

      <p class="text-xs text-cork-500">
        Role: <span class="font-medium capitalize">{user().role}</span>
      </p>
    </div>
  );
}

// Websites/Sonnet_4.6_EverThreadCo/src/components/profile/ProfileForm.tsx
"use client";

import Image from "next/image";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
import { Button } from "@/components/ui/Button";
import { roleLabel } from "@/lib/rbac";
import type { Role } from "@/generated/prisma/client";

export type ProfileUser = {
  id: string;
  username: string;
  email: string;
  role: Role;
  displayName: string | null;
  bio: string | null;
  avatarUrl: string | null;
};

type ProfileFormProps = {
  user: ProfileUser;
};

export function ProfileForm({ user }: ProfileFormProps) {
  const router = useRouter();
  const { update } = useSession();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [email, setEmail] = useState(user.email);
  const [displayName, setDisplayName] = useState(user.displayName ?? "");
  const [bio, setBio] = useState(user.bio ?? "");
  const [avatarUrl, setAvatarUrl] = useState(user.avatarUrl ?? "");
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmNewPassword, setConfirmNewPassword] = useState("");
  const [deletePassword, setDeletePassword] = useState("");

  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);

  const previewAvatar = avatarUrl.trim() || user.avatarUrl;

  async function handleAvatarUpload(file: File) {
    setUploading(true);
    setError(null);

    const formData = new FormData();
    formData.append("avatar", file);

    const res = await fetch("/api/profile/avatar", {
      method: "POST",
      body: formData,
    });
    const data = await res.json();
    setUploading(false);

    if (!res.ok) {
      setError(data.error ?? "Upload failed");
      return;
    }

    setAvatarUrl(data.avatarUrl);
    await update({
      user: { image: data.avatarUrl },
    });
    setMessage("Profile picture uploaded");
    router.refresh();
  }

  async function handleProfileSave(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setMessage(null);

    const res = await fetch("/api/profile", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email,
        displayName: displayName || null,
        bio: bio || null,
        avatarUrl: avatarUrl || null,
        currentPassword: currentPassword || undefined,
        newPassword: newPassword || undefined,
        confirmNewPassword: confirmNewPassword || undefined,
      }),
    });

    const data = await res.json();
    setLoading(false);

    if (!res.ok) {
      setError(data.error ?? "Update failed");
      return;
    }

    await update({
      user: {
        name: data.user.displayName ?? data.user.username,
        email: data.user.email,
        image: data.user.avatarUrl,
        displayName: data.user.displayName,
        bio: data.user.bio,
      },
    });

    setCurrentPassword("");
    setNewPassword("");
    setConfirmNewPassword("");
    setMessage("Profile saved successfully");
    router.refresh();
  }

  async function handleDeleteAccount(e: React.FormEvent) {
    e.preventDefault();
    if (
      !confirm(
        "This permanently deletes your account and cannot be undone. Continue?",
      )
    ) {
      return;
    }

    setLoading(true);
    setError(null);

    const res = await fetch("/api/profile", {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ password: deletePassword }),
    });

    const data = await res.json();
    setLoading(false);

    if (!res.ok) {
      setError(data.error ?? "Could not delete account");
      return;
    }

    await signOut({ callbackUrl: "/" });
  }

  return (
    <div className="mx-auto max-w-2xl px-6 py-12">
      <div className="mb-10">
        <h1 className="font-display text-4xl text-sand-900">Your profile</h1>
        <p className="mt-2 text-sm text-sand-600">
          @{user.username} · {roleLabel(user.role)}
        </p>
      </div>

      {message ? (
        <p className="mb-6 rounded-lg bg-sage-50 px-4 py-3 text-sm text-sage-800">
          {message}
        </p>
      ) : null}
      {error ? (
        <p className="mb-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800">
          {error}
        </p>
      ) : null}

      <section className="mb-10 rounded-2xl border border-sand-200 bg-cream-50 p-6">
        <h2 className="font-display text-xl text-sand-900">Profile picture</h2>
        <div className="mt-6 flex flex-col items-start gap-6 sm:flex-row sm:items-center">
          <div className="relative h-24 w-24 overflow-hidden rounded-full bg-sand-200 ring-2 ring-sand-300">
            {previewAvatar ? (
              <Image
                src={previewAvatar}
                alt="Profile"
                fill
                className="object-cover"
                unoptimized={previewAvatar.startsWith("/uploads/")}
              />
            ) : (
              <span className="flex h-full w-full items-center justify-center text-2xl font-medium text-sand-500">
                {user.username.slice(0, 1).toUpperCase()}
              </span>
            )}
          </div>

          <div className="flex flex-1 flex-col gap-4">
            <Input
              label="Image URL"
              name="avatarUrl"
              type="url"
              placeholder="https://example.com/photo.jpg"
              value={avatarUrl}
              onChange={(e) => setAvatarUrl(e.target.value)}
            />
            <div>
              <p className="mb-2 text-sm font-medium text-sand-800">
                Or upload a file (max 2 MB)
              </p>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/jpeg,image/png,image/webp,image/gif"
                className="text-sm text-sand-700 file:mr-4 file:rounded-full file:border-0 file:bg-sand-200 file:px-4 file:py-2 file:text-sm file:font-medium"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) void handleAvatarUpload(file);
                }}
              />
              {uploading ? (
                <p className="mt-2 text-xs text-sand-500">Uploading…</p>
              ) : null}
            </div>
          </div>
        </div>
      </section>

      <form
        onSubmit={handleProfileSave}
        className="space-y-10 rounded-2xl border border-sand-200 bg-cream-50 p-6"
      >
        <div>
          <h2 className="font-display text-xl text-sand-900">Account details</h2>
          <div className="mt-6 flex flex-col gap-5">
            <Input
              label="Username"
              name="username"
              value={user.username}
              disabled
              className="opacity-70"
            />
            <Input
              label="Email"
              name="email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Input
              label="Display name"
              name="displayName"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
            />
            <Textarea
              label="Bio"
              name="bio"
              value={bio}
              onChange={(e) => setBio(e.target.value)}
              placeholder="Tell us a little about yourself…"
            />
          </div>
        </div>

        <div>
          <h2 className="font-display text-xl text-sand-900">Change password</h2>
          <p className="mt-1 text-sm text-sand-600">
            Leave blank to keep your current password.
          </p>
          <div className="mt-6 flex flex-col gap-5">
            <Input
              label="Current password"
              name="currentPassword"
              type="password"
              autoComplete="current-password"
              value={currentPassword}
              onChange={(e) => setCurrentPassword(e.target.value)}
            />
            <Input
              label="New password"
              name="newPassword"
              type="password"
              autoComplete="new-password"
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
            />
            <Input
              label="Confirm new password"
              name="confirmNewPassword"
              type="password"
              autoComplete="new-password"
              value={confirmNewPassword}
              onChange={(e) => setConfirmNewPassword(e.target.value)}
            />
          </div>
        </div>

        <Button type="submit" disabled={loading} className="w-full sm:w-auto">
          {loading ? "Saving…" : "Save changes"}
        </Button>
      </form>

      <form
        onSubmit={handleDeleteAccount}
        className="mt-10 rounded-2xl border border-red-200 bg-red-50/50 p-6"
      >
        <h2 className="font-display text-xl text-red-900">Delete account</h2>
        <p className="mt-2 text-sm text-red-800/90">
          Permanently remove your account and all profile data. This action
          cannot be undone.
        </p>
        <div className="mt-6 max-w-md">
          <Input
            label="Confirm with your password"
            name="deletePassword"
            type="password"
            required
            value={deletePassword}
            onChange={(e) => setDeletePassword(e.target.value)}
          />
        </div>
        <Button
          type="submit"
          variant="secondary"
          disabled={loading}
          className="mt-6 border-red-300 text-red-900 hover:bg-red-100"
        >
          Delete my account
        </Button>
      </form>
    </div>
  );
}
