// Génération_Code_Application/Opus_RoastRitual/src/components/admin/ProductCsvImport.tsx
"use client";

import { useRef, useState } from "react";

import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Label } from "@/components/ui/Label";

type ImportError = {
  row: number;
  message: string;
};

type ProductCsvImportProps = {
  onImported: () => void;
};

const SAMPLE_CSV_PATH = "/samples/roastritual-products-import-sample.csv";

export function ProductCsvImport({ onImported }: ProductCsvImportProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState<{
    type: "success" | "error";
    text: string;
  } | null>(null);
  const [importErrors, setImportErrors] = useState<ImportError[]>([]);

  async function handleUpload(e: React.FormEvent) {
    e.preventDefault();
    setMessage(null);
    setImportErrors([]);

    const file = fileInputRef.current?.files?.[0];
    if (!file) {
      setMessage({ type: "error", text: "Choose a CSV file first." });
      return;
    }

    setUploading(true);
    const body = new FormData();
    body.append("file", file);

    try {
      const res = await fetch("/api/admin/products/import", {
        method: "POST",
        body,
      });
      const data = await res.json();

      if (!res.ok && !data.created) {
        setMessage({
          type: "error",
          text: data.error ?? "Import failed",
        });
        if (Array.isArray(data.errors)) {
          setImportErrors(data.errors as ImportError[]);
        }
        return;
      }

      const created = (data.created as number) ?? 0;
      const failed = (data.failed as number) ?? 0;

      setMessage({
        type: created > 0 ? "success" : "error",
        text:
          created > 0
            ? `Imported ${created} product${created !== 1 ? "s" : ""}${failed > 0 ? ` (${failed} row${failed !== 1 ? "s" : ""} skipped)` : ""}.`
            : "No products were imported.",
      });

      if (Array.isArray(data.errors) && data.errors.length > 0) {
        setImportErrors(data.errors as ImportError[]);
      }

      if (created > 0) {
        onImported();
        if (fileInputRef.current) fileInputRef.current.value = "";
      }
    } catch {
      setMessage({ type: "error", text: "Unable to reach the server." });
    } finally {
      setUploading(false);
    }
  }

  return (
    <section className="rounded-2xl border border-sage/25 bg-linen p-6">
      <h2 className="font-display text-xl text-espresso">Import products (CSV)</h2>
      <p className="mt-2 text-sm text-espresso/70">
        Upload a CSV file to create multiple products at once. Required columns:{" "}
        <span className="font-mono text-xs">name</span>,{" "}
        <span className="font-mono text-xs">description</span>,{" "}
        <span className="font-mono text-xs">category</span> (COFFEE or TEA),{" "}
        <span className="font-mono text-xs">price_dollars</span>. Optional: slug,
        image_url, origin, roast_level, is_ethical, is_active.
      </p>

      <p className="mt-3">
        <a
          href={SAMPLE_CSV_PATH}
          download="roastritual-products-import-sample.csv"
          className="text-sm font-medium text-sage-dark underline hover:text-espresso"
        >
          Download sample CSV template
        </a>
      </p>

      <form onSubmit={(e) => void handleUpload(e)} className="mt-6 space-y-4">
        {message && <Alert variant={message.type}>{message.text}</Alert>}

        <div>
          <Label htmlFor="product-csv-file">CSV file</Label>
          <input
            ref={fileInputRef}
            id="product-csv-file"
            type="file"
            accept=".csv,text/csv"
            className="mt-2 block w-full text-sm text-espresso/70 file:mr-4 file:rounded-full file:border-0 file:bg-sage/20 file:px-4 file:py-2 file:text-sm file:font-medium file:text-espresso hover:file:bg-sage/30"
          />
        </div>

        <Button type="submit" disabled={uploading}>
          {uploading ? "Importing…" : "Upload and import"}
        </Button>
      </form>

      {importErrors.length > 0 && (
        <div className="mt-6">
          <p className="text-sm font-medium text-espresso">Import issues</p>
          <ul className="mt-2 max-h-40 space-y-1 overflow-y-auto text-sm text-red-800">
            {importErrors.map((err, index) => (
              <li key={`${err.row}-${index}`}>
                {err.row > 0 ? `Row ${err.row}: ` : ""}
                {err.message}
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}

// Websites/GPT5.5_GamerGrid/src/components/solid/ProductCsvImport.tsx
import { createSignal, Show } from 'solid-js';
import type { ProductDTO } from '@/lib/types';

interface Props {
  categories: { id: string; name: string; slug: string }[];
  onImported: (products: ProductDTO[]) => void;
  onFlash: (message: string, isError?: boolean) => void;
}

type ImportResult = {
  created: number;
  failed: number;
  errors: { row: number; message: string }[];
};

export default function ProductCsvImport(props: Props) {
  const [file, setFile] = createSignal<File | null>(null);
  const [loading, setLoading] = createSignal(false);
  const [result, setResult] = createSignal<ImportResult | null>(null);

  const handleImport = async () => {
    const selected = file();
    if (!selected) {
      props.onFlash('Choose a CSV file first.', true);
      return;
    }

    setLoading(true);
    setResult(null);

    const formData = new FormData();
    formData.append('file', selected);

    try {
      const res = await fetch('/api/admin/products/import', {
        method: 'POST',
        body: formData,
      });
      const json = await res.json();

      if (!res.ok && !json.created) {
        throw new Error(json.error ?? 'Import failed.');
      }

      setResult({
        created: json.created ?? 0,
        failed: json.failed ?? 0,
        errors: json.errors ?? [],
      });

      if (json.products?.length) {
        props.onImported(json.products);
      }

      if (json.created > 0) {
        props.onFlash(
          `Imported ${json.created} product${json.created === 1 ? '' : 's'}${
            json.failed ? ` (${json.failed} row${json.failed === 1 ? '' : 's'} skipped)` : ''
          }.`,
        );
      } else {
        props.onFlash('No products were created. Check row errors below.', true);
      }

      setFile(null);
    } catch (err) {
      props.onFlash(err instanceof Error ? err.message : 'Import failed.', true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="rounded-2xl border border-stream-500/20 bg-slate-900/60 p-6 space-y-4">
      <div>
        <h3 class="text-lg font-semibold text-white">Import products from CSV</h3>
        <p class="mt-2 text-sm text-slate-400">
          Upload a comma-separated file to create multiple products at once. Download the{' '}
          <a
            href="/samples/products-import-sample.csv"
            class="font-medium text-volt-400 hover:text-volt-300 underline-offset-2 hover:underline"
            download
          >
            sample CSV
          </a>{' '}
          to see the required format.
        </p>
      </div>

      <dl class="grid gap-2 text-xs text-slate-500 sm:grid-cols-2">
        <div>
          <dt class="font-medium text-slate-400">Required columns</dt>
          <dd class="mt-1 font-mono">
            category_id <span class="text-slate-600">or</span> category_slug, name, description,
            price, image
          </dd>
        </div>
        <div>
          <dt class="font-medium text-slate-400">Optional columns</dt>
          <dd class="mt-1 font-mono">slug, badge, featured (true/false)</dd>
        </div>
      </dl>

      <Show when={props.categories.length > 0}>
        <p class="text-xs text-slate-500">
          Valid category IDs:{' '}
          {props.categories.map((c) => (
            <code class="mr-2 rounded bg-black/30 px-1 py-0.5 text-stream-400">{c.id}</code>
          ))}
        </p>
      </Show>

      <div class="flex flex-col gap-3 sm:flex-row sm:items-end">
        <label class="flex-1 text-sm">
          <span class="text-slate-400">CSV file</span>
          <input
            type="file"
            accept=".csv,text/csv"
            class="mt-1 block w-full text-sm text-slate-300 file:mr-4 file:rounded-full file:border-0 file:bg-volt-600 file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-volt-500"
            onChange={(e) => setFile(e.currentTarget.files?.[0] ?? null)}
          />
        </label>
        <button
          type="button"
          disabled={loading() || !file()}
          onClick={handleImport}
          class="rounded-full bg-stream-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-stream-500 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {loading() ? 'Importing…' : 'Upload & import'}
        </button>
      </div>

      <Show when={result()}>
        {(r) => (
          <div class="rounded-lg border border-white/10 bg-slate-950/50 p-4 text-sm">
            <p class="text-slate-300">
              <span class="font-medium text-stream-400">{r().created}</span> created ·{' '}
              <span class="font-medium text-amber-400">{r().failed}</span> failed
            </p>
            <Show when={r().errors.length > 0}>
              <ul class="mt-3 max-h-40 space-y-1 overflow-y-auto text-xs text-red-200/90">
                {r().errors.map((err) => (
                  <li>
                    Row {err.row}: {err.message}
                  </li>
                ))}
              </ul>
            </Show>
          </div>
        )}
      </Show>
    </div>
  );
}
