// Websites/GPT5.5_AeroPure/src/components/admin/ProductCsvImport.tsx
"use client";

import { useState } from "react";
import type { AdminProduct } from "@/types/admin";
import { Alert } from "@/components/ui/Alert";

type ProductCsvImportProps = {
  onImported: (products: AdminProduct[]) => void;
  onNotify: (msg: string | null) => void;
};

type ImportError = { row: number; slug?: string; message: string };

export function ProductCsvImport({
  onImported,
  onNotify,
}: ProductCsvImportProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{
    created: number;
    failed: number;
    errors: ImportError[];
  } | null>(null);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    setResult(null);
    setLoading(true);

    const form = e.currentTarget;
    const formData = new FormData(form);
    const file = formData.get("file");

    if (!file || !(file instanceof File) || file.size === 0) {
      setError("Please select a CSV file");
      setLoading(false);
      return;
    }

    try {
      const uploadData = new FormData();
      uploadData.append("file", file);

      const res = await fetch("/api/admin/products/import", {
        method: "POST",
        body: uploadData,
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error ?? "Import failed");
        return;
      }

      setResult({
        created: data.created,
        failed: data.failed,
        errors: data.errors ?? [],
      });

      if (data.products?.length) {
        onImported(data.products);
      }

      onNotify(data.message);
      form.reset();
    } catch {
      setError("Import failed. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-2xl border border-border bg-surface p-6">
      <h3 className="text-lg font-semibold">Import products from CSV</h3>
      <p className="mt-2 text-sm text-muted">
        Upload a CSV file to create multiple products at once. Download the
        template to see the required format.
      </p>

      <a
        href="/samples/products-import-template.csv"
        download="products-import-template.csv"
        className="mt-4 inline-block text-sm font-medium text-accent hover:underline"
      >
        Download sample CSV template →
      </a>

      <div className="mt-4 rounded-lg bg-border/20 p-4 text-xs text-muted">
        <p className="font-medium text-foreground">Required columns</p>
        <p className="mt-1 font-mono">
          slug, name, description, price, category
        </p>
        <p className="mt-3 font-medium text-foreground">Optional columns</p>
        <p className="mt-1 font-mono">featured, inStock, imageUrl</p>
        <p className="mt-3">
          Categories:{" "}
          <span className="font-mono">
            WIRELESS_CHARGING, SOLAR_POWER_BANK, TRAVEL_ORGANIZER
          </span>
        </p>
      </div>

      <form onSubmit={handleSubmit} className="mt-6 space-y-4">
        {error && <Alert type="error" message={error} />}
        {result && result.created > 0 && (
          <Alert
            type="success"
            message={`Successfully created ${result.created} product(s).`}
          />
        )}
        {result && result.failed > 0 && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200">
            <p className="font-medium">{result.failed} row(s) skipped</p>
            <ul className="mt-2 max-h-40 list-inside list-disc overflow-y-auto">
              {result.errors.map((err) => (
                <li key={`${err.row}-${err.slug ?? ""}`}>
                  Row {err.row}
                  {err.slug ? ` (${err.slug})` : ""}: {err.message}
                </li>
              ))}
            </ul>
          </div>
        )}

        <div>
          <label htmlFor="csv-file" className="block text-sm font-medium">
            CSV file
          </label>
          <input
            id="csv-file"
            name="file"
            type="file"
            accept=".csv,text/csv"
            required
            className="mt-1 w-full text-sm file:mr-4 file:rounded-lg file:border-0 file:bg-accent file:px-4 file:py-2 file:text-sm file:font-medium file:text-white"
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="rounded-full bg-accent px-6 py-2.5 text-sm font-semibold text-white hover:bg-accent-dark disabled:opacity-50"
        >
          {loading ? "Importing…" : "Upload and import"}
        </button>
      </form>
    </div>
  );
}

// Websites/GPT5.5_GamerGrid/src/components/solid/ProductCsvImport.tsx
import { createSignal, Show } from 'solid-js';
import type { ProductDTO } from '@/lib/types';

interface Props {
  categories: { id: string; name: string; slug: string }[];
  onImported: (products: ProductDTO[]) => void;
  onFlash: (message: string, isError?: boolean) => void;
}

type ImportResult = {
  created: number;
  failed: number;
  errors: { row: number; message: string }[];
};

export default function ProductCsvImport(props: Props) {
  const [file, setFile] = createSignal<File | null>(null);
  const [loading, setLoading] = createSignal(false);
  const [result, setResult] = createSignal<ImportResult | null>(null);

  const handleImport = async () => {
    const selected = file();
    if (!selected) {
      props.onFlash('Choose a CSV file first.', true);
      return;
    }

    setLoading(true);
    setResult(null);

    const formData = new FormData();
    formData.append('file', selected);

    try {
      const res = await fetch('/api/admin/products/import', {
        method: 'POST',
        body: formData,
      });
      const json = await res.json();

      if (!res.ok && !json.created) {
        throw new Error(json.error ?? 'Import failed.');
      }

      setResult({
        created: json.created ?? 0,
        failed: json.failed ?? 0,
        errors: json.errors ?? [],
      });

      if (json.products?.length) {
        props.onImported(json.products);
      }

      if (json.created > 0) {
        props.onFlash(
          `Imported ${json.created} product${json.created === 1 ? '' : 's'}${
            json.failed ? ` (${json.failed} row${json.failed === 1 ? '' : 's'} skipped)` : ''
          }.`,
        );
      } else {
        props.onFlash('No products were created. Check row errors below.', true);
      }

      setFile(null);
    } catch (err) {
      props.onFlash(err instanceof Error ? err.message : 'Import failed.', true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="rounded-2xl border border-stream-500/20 bg-slate-900/60 p-6 space-y-4">
      <div>
        <h3 class="text-lg font-semibold text-white">Import products from CSV</h3>
        <p class="mt-2 text-sm text-slate-400">
          Upload a comma-separated file to create multiple products at once. Download the{' '}
          <a
            href="/samples/products-import-sample.csv"
            class="font-medium text-volt-400 hover:text-volt-300 underline-offset-2 hover:underline"
            download
          >
            sample CSV
          </a>{' '}
          to see the required format.
        </p>
      </div>

      <dl class="grid gap-2 text-xs text-slate-500 sm:grid-cols-2">
        <div>
          <dt class="font-medium text-slate-400">Required columns</dt>
          <dd class="mt-1 font-mono">
            category_id <span class="text-slate-600">or</span> category_slug, name, description,
            price, image
          </dd>
        </div>
        <div>
          <dt class="font-medium text-slate-400">Optional columns</dt>
          <dd class="mt-1 font-mono">slug, badge, featured (true/false)</dd>
        </div>
      </dl>

      <Show when={props.categories.length > 0}>
        <p class="text-xs text-slate-500">
          Valid category IDs:{' '}
          {props.categories.map((c) => (
            <code class="mr-2 rounded bg-black/30 px-1 py-0.5 text-stream-400">{c.id}</code>
          ))}
        </p>
      </Show>

      <div class="flex flex-col gap-3 sm:flex-row sm:items-end">
        <label class="flex-1 text-sm">
          <span class="text-slate-400">CSV file</span>
          <input
            type="file"
            accept=".csv,text/csv"
            class="mt-1 block w-full text-sm text-slate-300 file:mr-4 file:rounded-full file:border-0 file:bg-volt-600 file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-volt-500"
            onChange={(e) => setFile(e.currentTarget.files?.[0] ?? null)}
          />
        </label>
        <button
          type="button"
          disabled={loading() || !file()}
          onClick={handleImport}
          class="rounded-full bg-stream-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-stream-500 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {loading() ? 'Importing…' : 'Upload & import'}
        </button>
      </div>

      <Show when={result()}>
        {(r) => (
          <div class="rounded-lg border border-white/10 bg-slate-950/50 p-4 text-sm">
            <p class="text-slate-300">
              <span class="font-medium text-stream-400">{r().created}</span> created ·{' '}
              <span class="font-medium text-amber-400">{r().failed}</span> failed
            </p>
            <Show when={r().errors.length > 0}>
              <ul class="mt-3 max-h-40 space-y-1 overflow-y-auto text-xs text-red-200/90">
                {r().errors.map((err) => (
                  <li>
                    Row {err.row}: {err.message}
                  </li>
                ))}
              </ul>
            </Show>
          </div>
        )}
      </Show>
    </div>
  );
}
